#include "DemocracySaveGameRuntime.h"

#include "Dom/JsonObject.h"
#include "HAL/FileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "Serialization/JsonWriter.h"

namespace
{
    FString Str(const TSharedPtr<FJsonObject>& O,const TCHAR* K,const FString& D=TEXT("")){ if(!O.IsValid()) return D; FString V; return O->TryGetStringField(K,V)?V:D; }
    int32 Int(const TSharedPtr<FJsonObject>& O,const TCHAR* K,int32 D=0){ if(!O.IsValid()) return D; int32 V=0; return O->TryGetNumberField(K,V)?V:D; }
    float Flt(const TSharedPtr<FJsonObject>& O,const TCHAR* K,float D=0.f){ if(!O.IsValid()) return D; double V=0; return O->TryGetNumberField(K,V)?static_cast<float>(V):D; }
    bool Bool(const TSharedPtr<FJsonObject>& O,const TCHAR* K,bool D=false){ if(!O.IsValid()) return D; bool V=false; return O->TryGetBoolField(K,V)?V:D; }
    TSharedPtr<FJsonObject> Obj(const TSharedPtr<FJsonObject>& O,const TCHAR* K){ const TSharedPtr<FJsonObject>* V=nullptr; return O.IsValid()&&O->TryGetObjectField(K,V)&&V?*V:nullptr; }
    TArray<FString> Strs(const TSharedPtr<FJsonObject>& O,const TCHAR* K){ TArray<FString> R; const TArray<TSharedPtr<FJsonValue>>* A=nullptr; if(O.IsValid()&&O->TryGetArrayField(K,A)&&A){ for(const auto& V:*A){ FString S; if(V.IsValid()&&V->TryGetString(S)) R.Add(S); } } return R; }
    template<typename T,typename F> void ObjArray(const TSharedPtr<FJsonObject>& O,const TCHAR* K,TArray<T>& Out,F Fn){ const TArray<TSharedPtr<FJsonValue>>* A=nullptr; if(O.IsValid()&&O->TryGetArrayField(K,A)&&A){ for(const auto& V:*A){ TSharedPtr<FJsonObject> VO=V.IsValid()?V->AsObject():nullptr; if(VO.IsValid()) Out.Add(Fn(VO)); } } }
    FString AutoPath(const FString& P){ return P+TEXT(".autosave"); }
    FString BakPath(const FString& P,int32 I){ return FString::Printf(TEXT("%s.bak%d"),*P,I); }
    TArray<FString> Candidates(const FString& P,bool PrimaryFirst){ TArray<FString> C; const FString A=AutoPath(P); if(PrimaryFirst){ C={P,A,BakPath(P,1),BakPath(A,1),BakPath(P,2),BakPath(A,2)}; } else { C={A,BakPath(A,1),BakPath(P,1),BakPath(A,2),BakPath(P,2),P}; } return C; }

    bool LoadRoot(const FString& P,TSharedPtr<FJsonObject>& Root,FString& Err)
    {
        FString S; if(!FFileHelper::LoadFileToString(S,*P)){ Err=FString::Printf(TEXT("Could not read save file: %s"),*P); return false; }
        const TSharedRef<TJsonReader<>> R=TJsonReaderFactory<>::Create(S); if(!FJsonSerializer::Deserialize(R,Root)||!Root.IsValid()){ Err=FString::Printf(TEXT("Save file is not valid JSON: %s"),*P); return false; }
        if(!Str(Root,TEXT("mode")).Equals(TEXT("SinglePlayer"),ESearchCase::IgnoreCase)){ Err=FString::Printf(TEXT("Save file is not a single-player save: %s"),*P); return false; }
        if(!Obj(Root,TEXT("currentGameState")).IsValid()&&!Obj(Root,TEXT("initialGameState")).IsValid()){ Err=FString::Printf(TEXT("Save file is missing game state data: %s"),*P); return false; }
        return true;
    }
    bool ValidSave(const FString& P){ if(!FPaths::FileExists(P)) return false; TSharedPtr<FJsonObject> R; FString E; return LoadRoot(P,R,E); }
    bool LoadRootFallback(const FString& P,TSharedPtr<FJsonObject>& R,FString& Err){ TArray<FString> Es; for(const FString& C:Candidates(P,true)){ if(!FPaths::FileExists(C)) continue; FString E; if(LoadRoot(C,R,E)) return true; Es.Add(E); } Err=Es.Num()?FString::Join(Es,TEXT("\n")):FString::Printf(TEXT("No readable save or backup file exists for %s"),*P); return false; }
    bool CopyIfExists(const FString& S,const FString& D,FString& E){ if(!FPaths::FileExists(S)) return true; FString C; if(!FFileHelper::LoadFileToString(C,*S)){ E=FString::Printf(TEXT("Could not read backup source: %s"),*S); return false; } if(!FFileHelper::SaveStringToFile(C,*D)){ E=FString::Printf(TEXT("Could not write backup file: %s"),*D); return false; } return true; }
    bool Rotate(const FString& P,FString& E){ if(!FPaths::FileExists(P)) return true; IFileManager::Get().Delete(*BakPath(P,2),false,true); return CopyIfExists(BakPath(P,1),BakPath(P,2),E)&&CopyIfExists(P,BakPath(P,1),E); }
    bool WriteProtected(const FString& P,const FString& C,bool bRotate,FString& E){ const FString T=P+TEXT(".tmp"); if(!FFileHelper::SaveStringToFile(C,*T)){ E=FString::Printf(TEXT("Could not write temporary save file: %s"),*T); return false; } if(!ValidSave(T)){ IFileManager::Get().Delete(*T,false,true); E=FString::Printf(TEXT("Temporary save failed validation: %s"),*T); return false; } if(bRotate&&!Rotate(P,E)){ IFileManager::Get().Delete(*T,false,true); return false; } if(!FFileHelper::SaveStringToFile(C,*P)){ IFileManager::Get().Delete(*T,false,true); E=FString::Printf(TEXT("Could not write updated save file: %s"),*P); return false; } IFileManager::Get().Delete(*T,false,true); return true; }

    FDemocracyResourceInventory ParseResources(const TSharedPtr<FJsonObject>& O){ FDemocracyResourceInventory R; R.Food=Int(O,TEXT("food"),R.Food); R.GasOil=Int(O,TEXT("gasOil"),R.GasOil); R.Wood=Int(O,TEXT("wood"),R.Wood); R.Metals=Int(O,TEXT("metals"),R.Metals); R.Water=Int(O,TEXT("water"),R.Water); return R; }
    FDemocracyPolicyState ParsePolicies(const TSharedPtr<FJsonObject>& O){ FDemocracyPolicyState P; P.EconomicPolicy=Str(O,TEXT("economicPolicy"),P.EconomicPolicy); P.EnvironmentalPolicy=Str(O,TEXT("environmentalPolicy"),P.EnvironmentalPolicy); P.MilitaryPolicy=Str(O,TEXT("militaryPolicy"),P.MilitaryPolicy); P.DiplomacyPolicy=Str(O,TEXT("diplomacyPolicy"),P.DiplomacyPolicy); P.CivilPolicy=Str(O,TEXT("civilPolicy"),P.CivilPolicy); P.PolicyChangeCount=Int(O,TEXT("policyChangeCount"),P.PolicyChangeCount); P.LastEconomicPolicyTurn=Int(O,TEXT("lastEconomicPolicyTurn"),P.LastEconomicPolicyTurn); P.LastEnvironmentalPolicyTurn=Int(O,TEXT("lastEnvironmentalPolicyTurn"),P.LastEnvironmentalPolicyTurn); P.LastMilitaryPolicyTurn=Int(O,TEXT("lastMilitaryPolicyTurn"),P.LastMilitaryPolicyTurn); P.LastDiplomacyPolicyTurn=Int(O,TEXT("lastDiplomacyPolicyTurn"),P.LastDiplomacyPolicyTurn); P.LastCivilPolicyTurn=Int(O,TEXT("lastCivilPolicyTurn"),P.LastCivilPolicyTurn); P.PolicyCooldownTurns=Int(O,TEXT("policyCooldownTurns"),P.PolicyCooldownTurns); P.LastPolicyChangeSummary=Str(O,TEXT("lastPolicyChangeSummary"),P.LastPolicyChangeSummary); P.ActivePolicyEffects=Strs(O,TEXT("activePolicyEffects")); P.PolicyRuleStatus=Strs(O,TEXT("policyRuleStatus")); return P; }
    FDemocracyCountryState ParseCountry(const TSharedPtr<FJsonObject>& O){ FDemocracyCountryState C; C.CountryName=Str(O,TEXT("countryName"),C.CountryName); C.LeaderGender=Str(O,TEXT("leaderGender"),C.LeaderGender); C.AddressTitle=Str(O,TEXT("addressTitle"),C.AddressTitle); C.Climate=Str(O,TEXT("climate"),C.Climate); C.Difficulty=Str(O,TEXT("difficulty"),C.Difficulty); C.CountrySize=Str(O,TEXT("countrySize"),C.CountrySize); C.CountrySizeScore=Int(O,TEXT("countrySizeScore"),C.CountrySizeScore); C.PublicApproval=Int(O,TEXT("publicApproval"),C.PublicApproval); C.Stability=Int(O,TEXT("stability"),C.Stability); C.Unrest=Int(O,TEXT("unrest"),C.Unrest); C.Treasury=Int(O,TEXT("treasury"),C.Treasury); C.EconomicHealth=Int(O,TEXT("economicHealth"),C.EconomicHealth); C.DiplomaticStanding=Int(O,TEXT("diplomaticStanding"),C.DiplomaticStanding); C.Technology=Int(O,TEXT("technology"),C.Technology); C.MilitaryReadiness=Int(O,TEXT("militaryReadiness"),C.MilitaryReadiness); C.Infrastructure=Int(O,TEXT("infrastructure"),C.Infrastructure); C.EnvironmentalHealth=Int(O,TEXT("environmentalHealth"),C.EnvironmentalHealth); C.Resources=ParseResources(Obj(O,TEXT("resources"))); C.Policies=ParsePolicies(Obj(O,TEXT("policies"))); return C; }
    FDemocracyFailureRiskState ParseFailure(const TSharedPtr<FJsonObject>& O){ FDemocracyFailureRiskState R; R.StabilityWarningThreshold=Int(O,TEXT("stabilityWarningThreshold"),R.StabilityWarningThreshold); R.StabilityCriticalThreshold=Int(O,TEXT("stabilityCriticalThreshold"),R.StabilityCriticalThreshold); R.UnrestWarningThreshold=Int(O,TEXT("unrestWarningThreshold"),R.UnrestWarningThreshold); R.UnrestCriticalThreshold=Int(O,TEXT("unrestCriticalThreshold"),R.UnrestCriticalThreshold); R.CurrentAssassinationRisk=Int(O,TEXT("currentAssassinationRisk"),R.CurrentAssassinationRisk); R.AssassinationRiskTrigger=Int(O,TEXT("assassinationRiskTrigger"),R.AssassinationRiskTrigger); R.WarningLevel=Str(O,TEXT("warningLevel"),R.WarningLevel); R.GameOverReason=Str(O,TEXT("gameOverReason"),R.GameOverReason); R.bGameOverOnAssassination=Bool(O,TEXT("gameOverOnAssassination"),R.bGameOverOnAssassination); R.ActiveUnrestCauses=Strs(O,TEXT("activeUnrestCauses")); R.AdvisorWarnings=Strs(O,TEXT("advisorWarnings")); R.RecoveryTips=Strs(O,TEXT("recoveryTips")); return R; }
    FDemocracyInvasionRiskState ParseInvasion(const TSharedPtr<FJsonObject>& O){ FDemocracyInvasionRiskState R; R.MilitaryReadinessWarningThreshold=Int(O,TEXT("militaryReadinessWarningThreshold"),R.MilitaryReadinessWarningThreshold); R.MilitaryReadinessCriticalThreshold=Int(O,TEXT("militaryReadinessCriticalThreshold"),R.MilitaryReadinessCriticalThreshold); R.BorderPressureWarningThreshold=Int(O,TEXT("borderPressureWarningThreshold"),R.BorderPressureWarningThreshold); R.BorderPressureCriticalThreshold=Int(O,TEXT("borderPressureCriticalThreshold"),R.BorderPressureCriticalThreshold); R.TerritorialLossWarningThreshold=Int(O,TEXT("territorialLossWarningThreshold"),R.TerritorialLossWarningThreshold); R.TerritorialLossCriticalThreshold=Int(O,TEXT("territorialLossCriticalThreshold"),R.TerritorialLossCriticalThreshold); R.CurrentInvasionRisk=Int(O,TEXT("currentInvasionRisk"),R.CurrentInvasionRisk); R.InvasionRiskTrigger=Int(O,TEXT("invasionRiskTrigger"),R.InvasionRiskTrigger); R.WarningLevel=Str(O,TEXT("warningLevel"),R.WarningLevel); R.GameOverReason=Str(O,TEXT("gameOverReason"),R.GameOverReason); R.bGameOverOnTakeover=Bool(O,TEXT("gameOverOnTakeover"),R.bGameOverOnTakeover); R.ActiveInvasionCauses=Strs(O,TEXT("activeInvasionCauses")); R.AdvisorWarnings=Strs(O,TEXT("advisorWarnings")); R.RecoveryTips=Strs(O,TEXT("recoveryTips")); return R; }    FDemocracyAdvisorReport ParseReport(const TSharedPtr<FJsonObject>& O){ FDemocracyAdvisorReport R; R.AdvisorName=Str(O,TEXT("advisorName"),R.AdvisorName); R.Category=Str(O,TEXT("category"),R.Category); R.IssueReport=Str(O,TEXT("issueReport"),R.IssueReport); R.Recommendation=Str(O,TEXT("recommendation"),R.Recommendation); R.Warning=Str(O,TEXT("warning"),R.Warning); R.TradeoffExplanation=Str(O,TEXT("tradeoffExplanation"),R.TradeoffExplanation); R.GuidanceLevel=Str(O,TEXT("guidanceLevel"),R.GuidanceLevel); R.Severity=Int(O,TEXT("severity"),R.Severity); return R; }
    FDemocracyAdvisorSystemState ParseAdvisor(const TSharedPtr<FJsonObject>& O){ FDemocracyAdvisorSystemState S; S.GuidanceLevel=Str(O,TEXT("guidanceLevel"),S.GuidanceLevel); S.AdvisorCount=Int(O,TEXT("advisorCount"),S.AdvisorCount); S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); ObjArray(O,TEXT("reports"),S.Reports,ParseReport); return S; }
    FDemocracyEventChoiceState ParseChoice(const TSharedPtr<FJsonObject>& O){ FDemocracyEventChoiceState C; C.ChoiceId=Str(O,TEXT("choiceId"),C.ChoiceId); C.Label=Str(O,TEXT("label"),C.Label); C.Description=Str(O,TEXT("description"),C.Description); C.ConsequencePreview=Str(O,TEXT("consequencePreview"),C.ConsequencePreview); C.ApprovalDelta=Int(O,TEXT("approvalDelta"),C.ApprovalDelta); C.StabilityDelta=Int(O,TEXT("stabilityDelta"),C.StabilityDelta); C.UnrestDelta=Int(O,TEXT("unrestDelta"),C.UnrestDelta); C.TreasuryDelta=Int(O,TEXT("treasuryDelta"),C.TreasuryDelta); C.EconomicDelta=Int(O,TEXT("economicDelta"),C.EconomicDelta); C.DiplomacyDelta=Int(O,TEXT("diplomacyDelta"),C.DiplomacyDelta); C.MilitaryDelta=Int(O,TEXT("militaryDelta"),C.MilitaryDelta); C.InfrastructureDelta=Int(O,TEXT("infrastructureDelta"),C.InfrastructureDelta); C.EnvironmentDelta=Int(O,TEXT("environmentDelta"),C.EnvironmentDelta); C.FoodDelta=Int(O,TEXT("foodDelta"),C.FoodDelta); C.WaterDelta=Int(O,TEXT("waterDelta"),C.WaterDelta); C.GasOilDelta=Int(O,TEXT("gasOilDelta"),C.GasOilDelta); C.WoodDelta=Int(O,TEXT("woodDelta"),C.WoodDelta); C.MetalsDelta=Int(O,TEXT("metalsDelta"),C.MetalsDelta); C.AssassinationRiskDelta=Int(O,TEXT("assassinationRiskDelta"),C.AssassinationRiskDelta); C.InvasionRiskDelta=Int(O,TEXT("invasionRiskDelta"),C.InvasionRiskDelta); return C; }
    FDemocracyActiveEventState ParseEvent(const TSharedPtr<FJsonObject>& O){ FDemocracyActiveEventState E; E.EventId=Str(O,TEXT("eventId"),E.EventId); E.EventType=Str(O,TEXT("eventType"),E.EventType); E.Title=Str(O,TEXT("title"),E.Title); E.Description=Str(O,TEXT("description"),E.Description); E.TriggerReason=Str(O,TEXT("triggerReason"),E.TriggerReason); E.CreatedTurn=Int(O,TEXT("createdTurn"),E.CreatedTurn); E.DeadlineTurn=Int(O,TEXT("deadlineTurn"),E.DeadlineTurn); E.Severity=Int(O,TEXT("severity"),E.Severity); E.bTriggered=Bool(O,TEXT("triggered"),E.bTriggered); E.bResolved=Bool(O,TEXT("resolved"),E.bResolved); E.CompletionState=Str(O,TEXT("completionState"),E.CompletionState); E.SelectedChoiceId=Str(O,TEXT("selectedChoiceId"),E.SelectedChoiceId); E.ResolutionSummary=Str(O,TEXT("resolutionSummary"),E.ResolutionSummary); E.UnresolvedPenaltySummary=Str(O,TEXT("unresolvedPenaltySummary"),E.UnresolvedPenaltySummary); E.FollowUpEventType=Str(O,TEXT("followUpEventType"),E.FollowUpEventType); E.FollowUpTitle=Str(O,TEXT("followUpTitle"),E.FollowUpTitle); E.FollowUpDescription=Str(O,TEXT("followUpDescription"),E.FollowUpDescription); E.FollowUpSeverityDelta=Int(O,TEXT("followUpSeverityDelta"),E.FollowUpSeverityDelta); ObjArray(O,TEXT("choices"),E.Choices,ParseChoice); return E; }
    FDemocracyEventSystemState ParseEvents(const TSharedPtr<FJsonObject>& O){ FDemocracyEventSystemState S; S.LastEventTurn=Int(O,TEXT("lastEventTurn"),S.LastEventTurn); S.EventCounter=Int(O,TEXT("eventCounter"),S.EventCounter); S.ActiveEventLimit=Int(O,TEXT("activeEventLimit"),S.ActiveEventLimit); S.EventHistory=Strs(O,TEXT("eventHistory")); ObjArray(O,TEXT("activeEvents"),S.ActiveEvents,ParseEvent); return S; }
    FDemocracyCitizenGroupState ParseGroup(const TSharedPtr<FJsonObject>& O){ FDemocracyCitizenGroupState G; G.GroupName=Str(O,TEXT("groupName"),G.GroupName); G.PopulationShare=Int(O,TEXT("populationShare"),G.PopulationShare); G.Approval=Int(O,TEXT("approval"),G.Approval); G.NeedFood=Int(O,TEXT("needFood"),G.NeedFood); G.NeedWater=Int(O,TEXT("needWater"),G.NeedWater); G.NeedJobs=Int(O,TEXT("needJobs"),G.NeedJobs); G.NeedSecurity=Int(O,TEXT("needSecurity"),G.NeedSecurity); G.NeedHealthcare=Int(O,TEXT("needHealthcare"),G.NeedHealthcare); G.UnrestPressure=Int(O,TEXT("unrestPressure"),G.UnrestPressure); G.UnrestSources=Strs(O,TEXT("unrestSources")); return G; }
    FDemocracyRegionState ParseRegion(const TSharedPtr<FJsonObject>& O){ FDemocracyRegionState R; R.RegionName=Str(O,TEXT("regionName"),R.RegionName); R.Climate=Str(O,TEXT("climate"),R.Climate); R.PopulationShare=Int(O,TEXT("populationShare"),R.PopulationShare); R.Approval=Int(O,TEXT("approval"),R.Approval); R.Stability=Int(O,TEXT("stability"),R.Stability); R.Unrest=Int(O,TEXT("unrest"),R.Unrest); R.FoodAccess=Int(O,TEXT("foodAccess"),R.FoodAccess); R.WaterAccess=Int(O,TEXT("waterAccess"),R.WaterAccess); R.Jobs=Int(O,TEXT("jobs"),R.Jobs); R.Security=Int(O,TEXT("security"),R.Security); R.Infrastructure=Int(O,TEXT("infrastructure"),R.Infrastructure); R.UnrestSources=Strs(O,TEXT("unrestSources")); return R; }
    FDemocracyDemographicsState ParseDemo(const TSharedPtr<FJsonObject>& O){ FDemocracyDemographicsState D; D.TotalPopulationThousands=Int(O,TEXT("totalPopulationThousands"),D.TotalPopulationThousands); D.AverageGroupApproval=Int(O,TEXT("averageGroupApproval"),D.AverageGroupApproval); D.AverageRegionalApproval=Int(O,TEXT("averageRegionalApproval"),D.AverageRegionalApproval); D.NationalNeedsPressure=Int(O,TEXT("nationalNeedsPressure"),D.NationalNeedsPressure); D.DemographicUnrestPressure=Int(O,TEXT("demographicUnrestPressure"),D.DemographicUnrestPressure); D.NationalUnrestSources=Strs(O,TEXT("nationalUnrestSources")); ObjArray(O,TEXT("citizenGroups"),D.CitizenGroups,ParseGroup); ObjArray(O,TEXT("regions"),D.Regions,ParseRegion); return D; }
    FDemocracyEconomyBudgetState ParseBudget(const TSharedPtr<FJsonObject>& O){ FDemocracyEconomyBudgetState B; B.TaxRate=Int(O,TEXT("taxRate"),B.TaxRate); B.TaxPolicy=Str(O,TEXT("taxPolicy"),B.TaxPolicy); B.PublicServicesSpending=Int(O,TEXT("publicServicesSpending"),B.PublicServicesSpending); B.InfrastructureSpending=Int(O,TEXT("infrastructureSpending"),B.InfrastructureSpending); B.DefenseSpending=Int(O,TEXT("defenseSpending"),B.DefenseSpending); B.Debt=Int(O,TEXT("debt"),B.Debt); B.Income=Int(O,TEXT("income"),B.Income); B.Expenses=Int(O,TEXT("expenses"),B.Expenses); B.Deficit=Int(O,TEXT("deficit"),B.Deficit); B.Inflation=Int(O,TEXT("inflation"),B.Inflation); B.PublicServices=Int(O,TEXT("publicServices"),B.PublicServices); B.ProductionEfficiency=Int(O,TEXT("productionEfficiency"),B.ProductionEfficiency); B.DebtCapacity=Int(O,TEXT("debtCapacity"),B.DebtCapacity); B.SpendingLimit=Int(O,TEXT("spendingLimit"),B.SpendingLimit); B.CreditStress=Int(O,TEXT("creditStress"),B.CreditStress); B.bSpendingLimited=Bool(O,TEXT("spendingLimited"),B.bSpendingLimited); B.SpendingPosture=Str(O,TEXT("spendingPosture"),B.SpendingPosture); B.BudgetConstraintStatus=Str(O,TEXT("budgetConstraintStatus"),B.BudgetConstraintStatus); B.LastBudgetSummary=Str(O,TEXT("lastBudgetSummary"),B.LastBudgetSummary); return B; }
    FDemocracyResourceChainEntry ParseChain(const TSharedPtr<FJsonObject>& O){ FDemocracyResourceChainEntry C; C.ResourceName=Str(O,TEXT("resourceName"),C.ResourceName); C.Production=Int(O,TEXT("production"),C.Production); C.Consumption=Int(O,TEXT("consumption"),C.Consumption); C.Imports=Int(O,TEXT("imports"),C.Imports); C.Exports=Int(O,TEXT("exports"),C.Exports); C.Reserve=Int(O,TEXT("reserve"),C.Reserve); C.ReserveTarget=Int(O,TEXT("reserveTarget"),C.ReserveTarget); C.Shortage=Int(O,TEXT("shortage"),C.Shortage); C.Surplus=Int(O,TEXT("surplus"),C.Surplus); C.StrategicValue=Int(O,TEXT("strategicValue"),C.StrategicValue); C.Role=Str(O,TEXT("role"),C.Role); C.Status=Str(O,TEXT("status"),C.Status); C.Drivers=Strs(O,TEXT("drivers")); return C; }
    FDemocracyResourceProductionChainState ParseChains(const TSharedPtr<FJsonObject>& O){ FDemocracyResourceProductionChainState S; S.TotalShortagePressure=Int(O,TEXT("totalShortagePressure"),S.TotalShortagePressure); S.TradeBalance=Int(O,TEXT("tradeBalance"),S.TradeBalance); S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); S.Summary=Str(O,TEXT("summary"),S.Summary); ObjArray(O,TEXT("chains"),S.Chains,ParseChain); return S; }
    FDemocracyDepartmentState ParseDept(const TSharedPtr<FJsonObject>& O){ FDemocracyDepartmentState D; D.DepartmentName=Str(O,TEXT("departmentName"),D.DepartmentName); D.MinisterTitle=Str(O,TEXT("ministerTitle"),D.MinisterTitle); D.Domain=Str(O,TEXT("domain"),D.Domain); D.BudgetShare=Int(O,TEXT("budgetShare"),D.BudgetShare); D.Staffing=Int(O,TEXT("staffing"),D.Staffing); D.Effectiveness=Int(O,TEXT("effectiveness"),D.Effectiveness); D.PublicTrust=Int(O,TEXT("publicTrust"),D.PublicTrust); D.Priority=Int(O,TEXT("priority"),D.Priority); D.CurrentAction=Str(O,TEXT("currentAction"),D.CurrentAction); D.PolicyInterface=Str(O,TEXT("policyInterface"),D.PolicyInterface); D.AdvisorySummary=Str(O,TEXT("advisorySummary"),D.AdvisorySummary); D.ActionEffects=Strs(O,TEXT("actionEffects")); return D; }
    FDemocracyDepartmentSystemState ParseDepts(const TSharedPtr<FJsonObject>& O){ FDemocracyDepartmentSystemState S; S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); S.Coordination=Int(O,TEXT("coordination"),S.Coordination); S.Summary=Str(O,TEXT("summary"),S.Summary); ObjArray(O,TEXT("departments"),S.Departments,ParseDept); return S; }
    FDemocracyApprovalCauseState ParseCause(const TSharedPtr<FJsonObject>& O){ FDemocracyApprovalCauseState C; C.CauseName=Str(O,TEXT("causeName"),C.CauseName); C.Category=Str(O,TEXT("category"),C.Category); C.ApprovalImpact=Int(O,TEXT("approvalImpact"),C.ApprovalImpact); C.UnrestImpact=Int(O,TEXT("unrestImpact"),C.UnrestImpact); C.StabilityImpact=Int(O,TEXT("stabilityImpact"),C.StabilityImpact); C.Severity=Int(O,TEXT("severity"),C.Severity); C.SourceMetric=Str(O,TEXT("sourceMetric"),C.SourceMetric); C.CurrentStatus=Str(O,TEXT("currentStatus"),C.CurrentStatus); C.SuggestedResponses=Strs(O,TEXT("suggestedResponses")); return C; }
    FDemocracyApprovalStabilityModelState ParseApproval(const TSharedPtr<FJsonObject>& O){ FDemocracyApprovalStabilityModelState S; S.NetApprovalPressure=Int(O,TEXT("netApprovalPressure"),S.NetApprovalPressure); S.NetUnrestPressure=Int(O,TEXT("netUnrestPressure"),S.NetUnrestPressure); S.NetStabilityPressure=Int(O,TEXT("netStabilityPressure"),S.NetStabilityPressure); S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); S.Summary=Str(O,TEXT("summary"),S.Summary); ObjArray(O,TEXT("causes"),S.Causes,ParseCause); return S; }    FDemocracyPressReleaseRecordState ParsePressRec(const TSharedPtr<FJsonObject>& O){ FDemocracyPressReleaseRecordState R; R.Turn=Int(O,TEXT("turn"),R.Turn); R.AnnouncementType=Str(O,TEXT("announcementType"),R.AnnouncementType); R.MessageQuality=Str(O,TEXT("messageQuality"),R.MessageQuality); R.bTruthful=Bool(O,TEXT("truthful"),R.bTruthful); R.ApprovalDelta=Int(O,TEXT("approvalDelta"),R.ApprovalDelta); R.StabilityDelta=Int(O,TEXT("stabilityDelta"),R.StabilityDelta); R.DiplomacyDelta=Int(O,TEXT("diplomacyDelta"),R.DiplomacyDelta); R.UnrestDelta=Int(O,TEXT("unrestDelta"),R.UnrestDelta); R.CredibilityDelta=Int(O,TEXT("credibilityDelta"),R.CredibilityDelta); R.CredibilityAfter=Int(O,TEXT("credibilityAfter"),R.CredibilityAfter); R.Summary=Str(O,TEXT("summary"),R.Summary); return R; }
    FDemocracyPressOfficeState ParsePress(const TSharedPtr<FJsonObject>& O){ FDemocracyPressOfficeState S; S.Credibility=Int(O,TEXT("credibility"),S.Credibility); S.ConsecutiveEmptyAnnouncements=Int(O,TEXT("consecutiveEmptyAnnouncements"),S.ConsecutiveEmptyAnnouncements); S.ConsecutiveFalseAnnouncements=Int(O,TEXT("consecutiveFalseAnnouncements"),S.ConsecutiveFalseAnnouncements); S.TotalAnnouncements=Int(O,TEXT("totalAnnouncements"),S.TotalAnnouncements); S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); S.MaxRecords=Int(O,TEXT("maxRecords"),S.MaxRecords); S.LastAnnouncementSummary=Str(O,TEXT("lastAnnouncementSummary"),S.LastAnnouncementSummary); ObjArray(O,TEXT("records"),S.Records,ParsePressRec); return S; }
    FDemocracyMeetingRecordState ParseMeetRec(const TSharedPtr<FJsonObject>& O){ FDemocracyMeetingRecordState R; R.Turn=Int(O,TEXT("turn"),R.Turn); R.MeetingType=Str(O,TEXT("meetingType"),R.MeetingType); R.ParticipantName=Str(O,TEXT("participantName"),R.ParticipantName); R.AgendaItem=Str(O,TEXT("agendaItem"),R.AgendaItem); R.OutcomeSummary=Str(O,TEXT("outcomeSummary"),R.OutcomeSummary); R.ApprovalDelta=Int(O,TEXT("approvalDelta"),R.ApprovalDelta); R.StabilityDelta=Int(O,TEXT("stabilityDelta"),R.StabilityDelta); R.UnrestDelta=Int(O,TEXT("unrestDelta"),R.UnrestDelta); R.DiplomacyDelta=Int(O,TEXT("diplomacyDelta"),R.DiplomacyDelta); R.TreasuryDelta=Int(O,TEXT("treasuryDelta"),R.TreasuryDelta); R.EconomyDelta=Int(O,TEXT("economyDelta"),R.EconomyDelta); R.MilitaryDelta=Int(O,TEXT("militaryDelta"),R.MilitaryDelta); R.InfrastructureDelta=Int(O,TEXT("infrastructureDelta"),R.InfrastructureDelta); R.AdvisorCoordinationDelta=Int(O,TEXT("advisorCoordinationDelta"),R.AdvisorCoordinationDelta); R.ForeignTrustDelta=Int(O,TEXT("foreignTrustDelta"),R.ForeignTrustDelta); return R; }
    FDemocracyMeetingSystemState ParseMeeting(const TSharedPtr<FJsonObject>& O){ FDemocracyMeetingSystemState S; S.TotalMeetings=Int(O,TEXT("totalMeetings"),S.TotalMeetings); S.AdvisorCoordination=Int(O,TEXT("advisorCoordination"),S.AdvisorCoordination); S.ForeignTrust=Int(O,TEXT("foreignTrust"),S.ForeignTrust); S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); S.MaxRecords=Int(O,TEXT("maxRecords"),S.MaxRecords); S.LastMeetingSummary=Str(O,TEXT("lastMeetingSummary"),S.LastMeetingSummary); ObjArray(O,TEXT("records"),S.Records,ParseMeetRec); return S; }
    FDemocracyDevelopmentTrackState ParseTrack(const TSharedPtr<FJsonObject>& O){ FDemocracyDevelopmentTrackState T; T.TrackName=Str(O,TEXT("trackName"),T.TrackName); T.FocusArea=Str(O,TEXT("focusArea"),T.FocusArea); T.Level=Int(O,TEXT("level"),T.Level); T.Progress=Int(O,TEXT("progress"),T.Progress); T.ProgressTarget=Int(O,TEXT("progressTarget"),T.ProgressTarget); T.TreasuryCost=Int(O,TEXT("treasuryCost"),T.TreasuryCost); T.WoodCost=Int(O,TEXT("woodCost"),T.WoodCost); T.MetalsCost=Int(O,TEXT("metalsCost"),T.MetalsCost); T.FuelCost=Int(O,TEXT("fuelCost"),T.FuelCost); T.CurrentProject=Str(O,TEXT("currentProject"),T.CurrentProject); T.StrategicBenefit=Str(O,TEXT("strategicBenefit"),T.StrategicBenefit); T.Unlocks=Strs(O,TEXT("unlocks")); return T; }
    FDemocracyDevelopmentSystemState ParseDevelopment(const TSharedPtr<FJsonObject>& O){ FDemocracyDevelopmentSystemState S; S.ActiveFocus=Str(O,TEXT("activeFocus"),S.ActiveFocus); S.DevelopmentPoints=Int(O,TEXT("developmentPoints"),S.DevelopmentPoints); S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); S.Summary=Str(O,TEXT("summary"),S.Summary); ObjArray(O,TEXT("tracks"),S.Tracks,ParseTrack); return S; }
    FDemocracyDecisionRecordState ParseDecision(const TSharedPtr<FJsonObject>& O){ FDemocracyDecisionRecordState R; R.Turn=Int(O,TEXT("turn"),R.Turn); R.Category=Str(O,TEXT("category"),R.Category); R.DecisionTitle=Str(O,TEXT("decisionTitle"),R.DecisionTitle); R.DecisionDetail=Str(O,TEXT("decisionDetail"),R.DecisionDetail); R.ConsequenceSummary=Str(O,TEXT("consequenceSummary"),R.ConsequenceSummary); R.ApprovalAfter=Int(O,TEXT("approvalAfter"),R.ApprovalAfter); R.StabilityAfter=Int(O,TEXT("stabilityAfter"),R.StabilityAfter); R.UnrestAfter=Int(O,TEXT("unrestAfter"),R.UnrestAfter); R.TreasuryAfter=Int(O,TEXT("treasuryAfter"),R.TreasuryAfter); R.EconomyAfter=Int(O,TEXT("economyAfter"),R.EconomyAfter); R.MilitaryAfter=Int(O,TEXT("militaryAfter"),R.MilitaryAfter); R.Severity=Int(O,TEXT("severity"),R.Severity); R.TimestampUtc=Str(O,TEXT("timestampUtc"),R.TimestampUtc); R.Tags=Strs(O,TEXT("tags")); return R; }
    FDemocracyDecisionHistoryState ParseHistory(const TSharedPtr<FJsonObject>& O){ FDemocracyDecisionHistoryState H; H.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),H.LastUpdatedTurn); H.MaxRecords=Int(O,TEXT("maxRecords"),H.MaxRecords); H.Summary=Str(O,TEXT("summary"),H.Summary); ObjArray(O,TEXT("records"),H.Records,ParseDecision); return H; }
    FDemocracyGeneratedCountryState ParseGenCountry(const TSharedPtr<FJsonObject>& O){ FDemocracyGeneratedCountryState C; C.CountryName=Str(O,TEXT("countryName"),C.CountryName); C.ContinentName=Str(O,TEXT("continentName"),C.ContinentName); C.Climate=Str(O,TEXT("climate"),C.Climate); C.PoliticalType=Str(O,TEXT("politicalType"),C.PoliticalType); C.DiplomaticAlignment=Str(O,TEXT("diplomaticAlignment"),C.DiplomaticAlignment); C.PowerScore=Int(O,TEXT("powerScore"),C.PowerScore); C.Stability=Int(O,TEXT("stability"),C.Stability); C.BorderPressure=Int(O,TEXT("borderPressure"),C.BorderPressure); C.bAlliedWithPlayer=Bool(O,TEXT("alliedWithPlayer"),C.bAlliedWithPlayer); return C; }
    FDemocracyContinentState ParseContinent(const TSharedPtr<FJsonObject>& O){ FDemocracyContinentState C; C.ContinentName=Str(O,TEXT("continentName"),C.ContinentName); C.Climate=Str(O,TEXT("climate"),C.Climate); C.CountryCount=Int(O,TEXT("countryCount"),C.CountryCount); ObjArray(O,TEXT("countries"),C.Countries,ParseGenCountry); return C; }
    FDemocracyWorldMapState ParseWorld(const TSharedPtr<FJsonObject>& O){ FDemocracyWorldMapState W; W.ContinentCount=Int(O,TEXT("continentCount"),W.ContinentCount); W.TotalCountryCount=Int(O,TEXT("totalCountryCount"),W.TotalCountryCount); W.DemocraticAllyCount=Int(O,TEXT("democraticAllyCount"),W.DemocraticAllyCount); W.NonDemocraticCountryCount=Int(O,TEXT("nonDemocraticCountryCount"),W.NonDemocraticCountryCount); W.GenerationRule=Str(O,TEXT("generationRule"),W.GenerationRule); ObjArray(O,TEXT("continents"),W.Continents,ParseContinent); return W; }
    FDemocracyDiplomacyRelationshipState ParseDiplomacyRelationship(const TSharedPtr<FJsonObject>& O){ FDemocracyDiplomacyRelationshipState R; R.CountryName=Str(O,TEXT("countryName"),R.CountryName); R.ContinentName=Str(O,TEXT("continentName"),R.ContinentName); R.GovernmentType=Str(O,TEXT("governmentType"),R.GovernmentType); R.RelationshipStatus=Str(O,TEXT("relationshipStatus"),R.RelationshipStatus); R.bTradePartner=Bool(O,TEXT("tradePartner"),R.bTradePartner); R.bSanctionsActive=Bool(O,TEXT("sanctionsActive"),R.bSanctionsActive); R.TreatyStatus=Str(O,TEXT("treatyStatus"),R.TreatyStatus); R.BorderTension=Int(O,TEXT("borderTension"),R.BorderTension); R.Trust=Int(O,TEXT("trust"),R.Trust); R.TradeValue=Int(O,TEXT("tradeValue"),R.TradeValue); R.LastChangedTurn=Int(O,TEXT("lastChangedTurn"),R.LastChangedTurn); R.ActiveTreaties=Strs(O,TEXT("activeTreaties")); R.Notes=Strs(O,TEXT("notes")); return R; }
    FDemocracyDiplomacyMatrixState ParseDiplomacyMatrix(const TSharedPtr<FJsonObject>& O){ FDemocracyDiplomacyMatrixState M; M.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),M.LastUpdatedTurn); M.AllyCount=Int(O,TEXT("allyCount"),M.AllyCount); M.NeutralCount=Int(O,TEXT("neutralCount"),M.NeutralCount); M.RivalCount=Int(O,TEXT("rivalCount"),M.RivalCount); M.HostileCount=Int(O,TEXT("hostileCount"),M.HostileCount); M.TradePartnerCount=Int(O,TEXT("tradePartnerCount"),M.TradePartnerCount); M.SanctionsCount=Int(O,TEXT("sanctionsCount"),M.SanctionsCount); M.TreatyCount=Int(O,TEXT("treatyCount"),M.TreatyCount); M.AverageBorderTension=Int(O,TEXT("averageBorderTension"),M.AverageBorderTension); M.Summary=Str(O,TEXT("summary"),M.Summary); ObjArray(O,TEXT("relationships"),M.Relationships,ParseDiplomacyRelationship); return M; }
    FDemocracyProvinceOwnershipState ParseProvinceOwnership(const TSharedPtr<FJsonObject>& O){ FDemocracyProvinceOwnershipState P; P.ProvinceId=Str(O,TEXT("provinceId"),P.ProvinceId); P.ProvinceName=Str(O,TEXT("provinceName"),P.ProvinceName); P.ContinentName=Str(O,TEXT("continentName"),P.ContinentName); P.OriginalCountryName=Str(O,TEXT("originalCountryName"),P.OriginalCountryName); P.CurrentOwnerCountryName=Str(O,TEXT("currentOwnerCountryName"),P.CurrentOwnerCountryName); P.CurrentControllerCountryName=Str(O,TEXT("currentControllerCountryName"),P.CurrentControllerCountryName); P.GovernmentType=Str(O,TEXT("governmentType"),P.GovernmentType); P.Climate=Str(O,TEXT("climate"),P.Climate); P.ResourceFocus=Str(O,TEXT("resourceFocus"),P.ResourceFocus); P.StrategicValue=Int(O,TEXT("strategicValue"),P.StrategicValue); P.Stability=Int(O,TEXT("stability"),P.Stability); P.Unrest=Int(O,TEXT("unrest"),P.Unrest); P.bPlayerControlled=Bool(O,TEXT("playerControlled"),P.bPlayerControlled); P.bBorderProvince=Bool(O,TEXT("borderProvince"),P.bBorderProvince); P.LastChangedTurn=Int(O,TEXT("lastChangedTurn"),P.LastChangedTurn); return P; }
    FDemocracyCountryOwnershipState ParseCountryOwnership(const TSharedPtr<FJsonObject>& O){ FDemocracyCountryOwnershipState C; C.CountryName=Str(O,TEXT("countryName"),C.CountryName); C.ContinentName=Str(O,TEXT("continentName"),C.ContinentName); C.GovernmentType=Str(O,TEXT("governmentType"),C.GovernmentType); C.TotalProvinces=Int(O,TEXT("totalProvinces"),C.TotalProvinces); C.ControlledProvinces=Int(O,TEXT("controlledProvinces"),C.ControlledProvinces); C.OccupiedProvinces=Int(O,TEXT("occupiedProvinces"),C.OccupiedProvinces); C.LostProvinces=Int(O,TEXT("lostProvinces"),C.LostProvinces); C.BorderProvinces=Int(O,TEXT("borderProvinces"),C.BorderProvinces); C.ResourceBase=Int(O,TEXT("resourceBase"),C.ResourceBase); C.MilitaryValue=Int(O,TEXT("militaryValue"),C.MilitaryValue); C.bPlayerCountry=Bool(O,TEXT("playerCountry"),C.bPlayerCountry); C.bCapitalControlled=Bool(O,TEXT("capitalControlled"),C.bCapitalControlled); C.ProvinceIds=Strs(O,TEXT("provinceIds")); return C; }
    FDemocracyContinentOwnershipState ParseContinentOwnership(const TSharedPtr<FJsonObject>& O){ FDemocracyContinentOwnershipState C; C.ContinentName=Str(O,TEXT("continentName"),C.ContinentName); C.Climate=Str(O,TEXT("climate"),C.Climate); C.CountryCount=Int(O,TEXT("countryCount"),C.CountryCount); C.ProvinceCount=Int(O,TEXT("provinceCount"),C.ProvinceCount); C.PlayerControlledProvinces=Int(O,TEXT("playerControlledProvinces"),C.PlayerControlledProvinces); C.ContestedProvinces=Int(O,TEXT("contestedProvinces"),C.ContestedProvinces); C.CountryNames=Strs(O,TEXT("countryNames")); return C; }
    FDemocracyMapOwnershipState ParseMapOwnership(const TSharedPtr<FJsonObject>& O){ FDemocracyMapOwnershipState M; M.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),M.LastUpdatedTurn); M.TotalCountries=Int(O,TEXT("totalCountries"),M.TotalCountries); M.TotalProvinces=Int(O,TEXT("totalProvinces"),M.TotalProvinces); M.PlayerControlledProvinces=Int(O,TEXT("playerControlledProvinces"),M.PlayerControlledProvinces); M.ContestedProvinces=Int(O,TEXT("contestedProvinces"),M.ContestedProvinces); M.BorderProvinceCount=Int(O,TEXT("borderProvinceCount"),M.BorderProvinceCount); M.PlayerCountryName=Str(O,TEXT("playerCountryName"),M.PlayerCountryName); M.Summary=Str(O,TEXT("summary"),M.Summary); ObjArray(O,TEXT("provinces"),M.Provinces,ParseProvinceOwnership); ObjArray(O,TEXT("countries"),M.Countries,ParseCountryOwnership); ObjArray(O,TEXT("continents"),M.Continents,ParseContinentOwnership); return M; }
    FDemocracyRtsOutcomeState ParseRtsOutcome(const TSharedPtr<FJsonObject>& O){ FDemocracyRtsOutcomeState R; R.Turn=Int(O,TEXT("turn"),R.Turn); R.OutcomeId=Str(O,TEXT("outcomeId"),R.OutcomeId); R.ConflictName=Str(O,TEXT("conflictName"),R.ConflictName); R.OpponentCountry=Str(O,TEXT("opponentCountry"),R.OpponentCountry); R.OutcomeType=Str(O,TEXT("outcomeType"),R.OutcomeType); R.TerritoryDelta=Int(O,TEXT("territoryDelta"),R.TerritoryDelta); R.Casualties=Int(O,TEXT("casualties"),R.Casualties); R.ResourceDisruption=Int(O,TEXT("resourceDisruption"),R.ResourceDisruption); R.WarFatigueDelta=Int(O,TEXT("warFatigueDelta"),R.WarFatigueDelta); R.DiplomaticDamage=Int(O,TEXT("diplomaticDamage"),R.DiplomaticDamage); R.StabilityDelta=Int(O,TEXT("stabilityDelta"),R.StabilityDelta); R.InvasionRiskDelta=Int(O,TEXT("invasionRiskDelta"),R.InvasionRiskDelta); R.BudgetStrain=Int(O,TEXT("budgetStrain"),R.BudgetStrain); R.bAppliedToSimulation=Bool(O,TEXT("appliedToSimulation"),R.bAppliedToSimulation); R.Summary=Str(O,TEXT("summary"),R.Summary); R.ConsequenceTags=Strs(O,TEXT("consequenceTags")); return R; }
    FDemocracyRtsBackflowState ParseRtsBackflow(const TSharedPtr<FJsonObject>& O){ FDemocracyRtsBackflowState B; B.LastAppliedTurn=Int(O,TEXT("lastAppliedTurn"),B.LastAppliedTurn); B.PendingOutcomeCount=Int(O,TEXT("pendingOutcomeCount"),B.PendingOutcomeCount); B.TotalTerritoryDelta=Int(O,TEXT("totalTerritoryDelta"),B.TotalTerritoryDelta); B.TotalCasualties=Int(O,TEXT("totalCasualties"),B.TotalCasualties); B.WarFatigue=Int(O,TEXT("warFatigue"),B.WarFatigue); B.ResourceDisruptionPressure=Int(O,TEXT("resourceDisruptionPressure"),B.ResourceDisruptionPressure); B.BudgetStrainPressure=Int(O,TEXT("budgetStrainPressure"),B.BudgetStrainPressure); B.DiplomaticDamagePressure=Int(O,TEXT("diplomaticDamagePressure"),B.DiplomaticDamagePressure); B.LastOutcomeSummary=Str(O,TEXT("lastOutcomeSummary"),B.LastOutcomeSummary); ObjArray(O,TEXT("pendingOutcomes"),B.PendingOutcomes,ParseRtsOutcome); ObjArray(O,TEXT("outcomeHistory"),B.OutcomeHistory,ParseRtsOutcome); B.PendingOutcomeCount=B.PendingOutcomes.Num(); return B; }
    FDemocracyRivalCountryState ParseRival(const TSharedPtr<FJsonObject>& O){ FDemocracyRivalCountryState R; R.CountryName=Str(O,TEXT("countryName"),R.CountryName); R.Temperament=Str(O,TEXT("temperament"),R.Temperament); R.RelationToPlayer=Str(O,TEXT("relationToPlayer"),R.RelationToPlayer); R.PowerScore=Int(O,TEXT("powerScore"),R.PowerScore); R.BorderPressure=Int(O,TEXT("borderPressure"),R.BorderPressure); R.TradeValue=Int(O,TEXT("tradeValue"),R.TradeValue); return R; }
    FDemocracyRtsWorldState ParseRts(const TSharedPtr<FJsonObject>& O){ FDemocracyRtsWorldState R; R.SimulationSecond=Int(O,TEXT("simulationSecond"),R.SimulationSecond); R.ControlledTerritories=Int(O,TEXT("controlledTerritories"),R.ControlledTerritories); R.BorderTerritories=Int(O,TEXT("borderTerritories"),R.BorderTerritories); R.KnownRivalCountries=Int(O,TEXT("knownRivalCountries"),R.KnownRivalCountries); R.ActiveStrategicLayers=Strs(O,TEXT("activeStrategicLayers")); ObjArray(O,TEXT("rivals"),R.Rivals,ParseRival); R.Backflow=ParseRtsBackflow(Obj(O,TEXT("backflow"))); R.Ownership=ParseMapOwnership(Obj(O,TEXT("ownership"))); return R; }
    FDemocracyCommandAuthorityActionState ParseCommandAuthorityAction(const TSharedPtr<FJsonObject>& O){ FDemocracyCommandAuthorityActionState A; A.CommandId=Str(O,TEXT("commandId"),A.CommandId); A.Label=Str(O,TEXT("label"),A.Label); A.AuthorityLayer=Str(O,TEXT("authorityLayer"),A.AuthorityLayer); A.CommandType=Str(O,TEXT("commandType"),A.CommandType); A.ExecutionSurface=Str(O,TEXT("executionSurface"),A.ExecutionSurface); A.bOfficeAllowed=Bool(O,TEXT("officeAllowed"),A.bOfficeAllowed); A.bRtsViewAllowed=Bool(O,TEXT("rtsViewAllowed"),A.bRtsViewAllowed); A.bEnabled=Bool(O,TEXT("enabled"),A.bEnabled); A.CooldownTurns=Int(O,TEXT("cooldownTurns"),A.CooldownTurns); A.LastExecutedTurn=Int(O,TEXT("lastExecutedTurn"),A.LastExecutedTurn); A.TreasuryCost=Int(O,TEXT("treasuryCost"),A.TreasuryCost); A.ApprovalDelta=Int(O,TEXT("approvalDelta"),A.ApprovalDelta); A.StabilityDelta=Int(O,TEXT("stabilityDelta"),A.StabilityDelta); A.UnrestDelta=Int(O,TEXT("unrestDelta"),A.UnrestDelta); A.DiplomacyDelta=Int(O,TEXT("diplomacyDelta"),A.DiplomacyDelta); A.MilitaryDelta=Int(O,TEXT("militaryDelta"),A.MilitaryDelta); A.InvasionRiskDelta=Int(O,TEXT("invasionRiskDelta"),A.InvasionRiskDelta); A.ResourceDelta=Int(O,TEXT("resourceDelta"),A.ResourceDelta); A.Prerequisite=Str(O,TEXT("prerequisite"),A.Prerequisite); A.EffectPreview=Str(O,TEXT("effectPreview"),A.EffectPreview); A.DisabledReason=Str(O,TEXT("disabledReason"),A.DisabledReason); return A; }
    FDemocracyCommandAuthorityState ParseCommandAuthority(const TSharedPtr<FJsonObject>& O){ FDemocracyCommandAuthorityState C; C.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),C.LastUpdatedTurn); C.ActiveCommandPosture=Str(O,TEXT("activeCommandPosture"),C.ActiveCommandPosture); C.OfficeAuthoritySummary=Str(O,TEXT("officeAuthoritySummary"),C.OfficeAuthoritySummary); C.RtsAuthoritySummary=Str(O,TEXT("rtsAuthoritySummary"),C.RtsAuthoritySummary); C.LastCommandSummary=Str(O,TEXT("lastCommandSummary"),C.LastCommandSummary); ObjArray(O,TEXT("actions"),C.Actions,ParseCommandAuthorityAction); return C; }
    FDemocracyObjectiveState ParseObjective(const TSharedPtr<FJsonObject>& O){ FDemocracyObjectiveState V; V.Mode=Str(O,TEXT("mode"),V.Mode); V.PlayerGovernmentType=Str(O,TEXT("playerGovernmentType"),V.PlayerGovernmentType); V.GovernmentTransitionTarget=Str(O,TEXT("governmentTransitionTarget"),V.GovernmentTransitionTarget); V.GovernmentTransitionProgress=Int(O,TEXT("governmentTransitionProgress"),V.GovernmentTransitionProgress); V.GovernmentTransitionTurnsRemaining=Int(O,TEXT("governmentTransitionTurnsRemaining"),V.GovernmentTransitionTurnsRemaining); V.DemocraticCountryCount=Int(O,TEXT("democraticCountryCount"),V.DemocraticCountryCount); V.DictatorshipCountryCount=Int(O,TEXT("dictatorshipCountryCount"),V.DictatorshipCountryCount); V.OtherGovernmentCount=Int(O,TEXT("otherGovernmentCount"),V.OtherGovernmentCount); V.bSoftVictoryAchieved=Bool(O,TEXT("softVictoryAchieved"),V.bSoftVictoryAchieved); V.SoftVictoryTurn=Int(O,TEXT("softVictoryTurn"),V.SoftVictoryTurn); V.bSimulationContinuesAfterVictory=Bool(O,TEXT("simulationContinuesAfterVictory"),V.bSimulationContinuesAfterVictory); V.RegressionRisk=Int(O,TEXT("regressionRisk"),V.RegressionRisk); V.LongTermObjective=Str(O,TEXT("longTermObjective"),V.LongTermObjective); V.ObjectiveSummary=Str(O,TEXT("objectiveSummary"),V.ObjectiveSummary); V.ActiveObjectiveNotes=Strs(O,TEXT("activeObjectiveNotes")); V.AllianceRules=Strs(O,TEXT("allianceRules")); return V; }

    FDemocracySimulationState ParseState(const TSharedPtr<FJsonObject>& O){ FDemocracySimulationState S; S.Turn=Int(O,TEXT("turn"),S.Turn); S.Phase=Str(O,TEXT("phase"),S.Phase); S.RealTimeTickSeconds=Flt(O,TEXT("realTimeTickSeconds"),S.RealTimeTickSeconds); S.bPaused=Bool(O,TEXT("paused"),S.bPaused); S.PlayerCountry=ParseCountry(Obj(O,TEXT("playerCountry"))); S.FailureRisk=ParseFailure(Obj(O,TEXT("failureRisk"))); S.InvasionRisk=ParseInvasion(Obj(O,TEXT("invasionRisk"))); S.AdvisorSystem=ParseAdvisor(Obj(O,TEXT("advisorSystem"))); S.EventSystem=ParseEvents(Obj(O,TEXT("eventSystem"))); S.Demographics=ParseDemo(Obj(O,TEXT("demographics"))); S.EconomyBudget=ParseBudget(Obj(O,TEXT("economyBudget"))); S.ResourceChains=ParseChains(Obj(O,TEXT("resourceChains"))); S.Departments=ParseDepts(Obj(O,TEXT("departments"))); S.ApprovalStability=ParseApproval(Obj(O,TEXT("approvalStability"))); S.PressOffice=ParsePress(Obj(O,TEXT("pressOffice"))); S.MeetingSystem=ParseMeeting(Obj(O,TEXT("meetingSystem"))); S.DevelopmentSystem=ParseDevelopment(Obj(O,TEXT("developmentSystem"))); S.DecisionHistory=ParseHistory(Obj(O,TEXT("decisionHistory"))); S.WorldMap=ParseWorld(Obj(O,TEXT("worldMap"))); S.DiplomacyMatrix=ParseDiplomacyMatrix(Obj(O,TEXT("diplomacyMatrix"))); S.RtsWorld=ParseRts(Obj(O,TEXT("rtsWorld"))); S.CommandAuthority=ParseCommandAuthority(Obj(O,TEXT("commandAuthority"))); S.ObjectiveState=ParseObjective(Obj(O,TEXT("objectiveState"))); return S; }

    void AppendStringArraySignature(FString& Out,const TCHAR* Label,const TArray<FString>& Values){ Out += FString::Printf(TEXT("|%s[%d]"),Label,Values.Num()); for(const FString& V:Values){ Out += TEXT(":"); Out += V; } }
    void AppendResourceSignature(FString& Out,const FDemocracyResourceInventory& R){ Out += FString::Printf(TEXT("|res=%d,%d,%d,%d,%d"),R.Food,R.GasOil,R.Wood,R.Metals,R.Water); }
    FString PersistentRuntimeSignature(const FDemocracySimulationState& S)
    {
        FString Out;
        const FDemocracyCountryState& C=S.PlayerCountry;
        Out += FString::Printf(TEXT("turn=%d|phase=%s|ticks=%d|paused=%d|country=%s|gender=%s|title=%s|climate=%s|difficulty=%s|size=%s,%d|signals=%d,%d,%d,%d,%d,%d,%d,%d,%d,%d"),S.Turn,*S.Phase,FMath::RoundToInt(S.RealTimeTickSeconds*100.f),S.bPaused?1:0,*C.CountryName,*C.LeaderGender,*C.AddressTitle,*C.Climate,*C.Difficulty,*C.CountrySize,C.CountrySizeScore,C.PublicApproval,C.Stability,C.Unrest,C.Treasury,C.EconomicHealth,C.DiplomaticStanding,C.Technology,C.MilitaryReadiness,C.Infrastructure,C.EnvironmentalHealth);
        AppendResourceSignature(Out,C.Resources);
        Out += FString::Printf(TEXT("|pol=%s,%s,%s,%s,%s,%d,%d,%d,%d,%d,%d,%d,%s"),*C.Policies.EconomicPolicy,*C.Policies.EnvironmentalPolicy,*C.Policies.MilitaryPolicy,*C.Policies.DiplomacyPolicy,*C.Policies.CivilPolicy,C.Policies.PolicyChangeCount,C.Policies.LastEconomicPolicyTurn,C.Policies.LastEnvironmentalPolicyTurn,C.Policies.LastMilitaryPolicyTurn,C.Policies.LastDiplomacyPolicyTurn,C.Policies.LastCivilPolicyTurn,C.Policies.PolicyCooldownTurns,*C.Policies.LastPolicyChangeSummary);
        AppendStringArraySignature(Out,TEXT("policyEffects"),C.Policies.ActivePolicyEffects); AppendStringArraySignature(Out,TEXT("policyRules"),C.Policies.PolicyRuleStatus);

        const FDemocracyFailureRiskState& F=S.FailureRisk;
        Out += FString::Printf(TEXT("|fail=%d,%d,%d,%d,%d,%d,%s,%s,%d"),F.StabilityWarningThreshold,F.StabilityCriticalThreshold,F.UnrestWarningThreshold,F.UnrestCriticalThreshold,F.CurrentAssassinationRisk,F.AssassinationRiskTrigger,*F.WarningLevel,*F.GameOverReason,F.bGameOverOnAssassination?1:0);
        AppendStringArraySignature(Out,TEXT("failCauses"),F.ActiveUnrestCauses); AppendStringArraySignature(Out,TEXT("failWarnings"),F.AdvisorWarnings); AppendStringArraySignature(Out,TEXT("failTips"),F.RecoveryTips);
        const FDemocracyInvasionRiskState& I=S.InvasionRisk;
        Out += FString::Printf(TEXT("|inv=%d,%d,%d,%d,%d,%d,%d,%d,%s,%s,%d"),I.MilitaryReadinessWarningThreshold,I.MilitaryReadinessCriticalThreshold,I.BorderPressureWarningThreshold,I.BorderPressureCriticalThreshold,I.TerritorialLossWarningThreshold,I.TerritorialLossCriticalThreshold,I.CurrentInvasionRisk,I.InvasionRiskTrigger,*I.WarningLevel,*I.GameOverReason,I.bGameOverOnTakeover?1:0);
        AppendStringArraySignature(Out,TEXT("invCauses"),I.ActiveInvasionCauses); AppendStringArraySignature(Out,TEXT("invWarnings"),I.AdvisorWarnings); AppendStringArraySignature(Out,TEXT("invTips"),I.RecoveryTips);

        const FDemocracyCommandAuthorityState& CA=S.CommandAuthority;
        Out += FString::Printf(TEXT("|cmdAuth=%d,%s,%s,%s,%s,%d"),CA.LastUpdatedTurn,*CA.ActiveCommandPosture,*CA.OfficeAuthoritySummary,*CA.RtsAuthoritySummary,*CA.LastCommandSummary,CA.Actions.Num());
        for(const FDemocracyCommandAuthorityActionState& CommandAction:CA.Actions){ Out += FString::Printf(TEXT("|cmd=%s,%s,%s,%s,%s,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%s,%s,%s"),*CommandAction.CommandId,*CommandAction.Label,*CommandAction.AuthorityLayer,*CommandAction.CommandType,*CommandAction.ExecutionSurface,CommandAction.bOfficeAllowed?1:0,CommandAction.bRtsViewAllowed?1:0,CommandAction.bEnabled?1:0,CommandAction.CooldownTurns,CommandAction.LastExecutedTurn,CommandAction.TreasuryCost,CommandAction.ApprovalDelta,CommandAction.StabilityDelta,CommandAction.UnrestDelta,CommandAction.DiplomacyDelta,CommandAction.MilitaryDelta,CommandAction.InvasionRiskDelta,CommandAction.ResourceDelta,*CommandAction.Prerequisite,*CommandAction.EffectPreview,*CommandAction.DisabledReason); }
        const FDemocracyObjectiveState& O=S.ObjectiveState;
        Out += FString::Printf(TEXT("|obj=%s,%s,%s,%d,%d,%d,%d,%d,%d,%d,%d,%d,%s,%s"),*O.Mode,*O.PlayerGovernmentType,*O.GovernmentTransitionTarget,O.GovernmentTransitionProgress,O.GovernmentTransitionTurnsRemaining,O.DemocraticCountryCount,O.DictatorshipCountryCount,O.OtherGovernmentCount,O.bSoftVictoryAchieved?1:0,O.SoftVictoryTurn,O.bSimulationContinuesAfterVictory?1:0,O.RegressionRisk,*O.LongTermObjective,*O.ObjectiveSummary);
        AppendStringArraySignature(Out,TEXT("objNotes"),O.ActiveObjectiveNotes); AppendStringArraySignature(Out,TEXT("objRules"),O.AllianceRules);

        const FDemocracyAdvisorSystemState& A=S.AdvisorSystem;
        Out += FString::Printf(TEXT("|advisor=%s,%d,%d,%d"),*A.GuidanceLevel,A.AdvisorCount,A.LastUpdatedTurn,A.Reports.Num());
        for(const FDemocracyAdvisorReport& R:A.Reports){ Out += FString::Printf(TEXT("|ar=%s,%s,%d,%s,%s,%s,%s,%s"),*R.AdvisorName,*R.Category,R.Severity,*R.GuidanceLevel,*R.IssueReport,*R.Recommendation,*R.Warning,*R.TradeoffExplanation); }

        const FDemocracyEventSystemState& E=S.EventSystem;
        Out += FString::Printf(TEXT("|events=%d,%d,%d,%d,%d"),E.LastEventTurn,E.EventCounter,E.ActiveEventLimit,E.ActiveEvents.Num(),E.EventHistory.Num()); AppendStringArraySignature(Out,TEXT("eventHistory"),E.EventHistory);
        for(const FDemocracyActiveEventState& Ev:E.ActiveEvents){ Out += FString::Printf(TEXT("|ev=%s,%s,%s,%s,%s,%d,%d,%d,%d,%d,%s,%s,%s,%s,%s,%s,%d,%d"),*Ev.EventId,*Ev.EventType,*Ev.Title,*Ev.Description,*Ev.TriggerReason,Ev.CreatedTurn,Ev.DeadlineTurn,Ev.Severity,Ev.bTriggered?1:0,Ev.bResolved?1:0,*Ev.CompletionState,*Ev.SelectedChoiceId,*Ev.ResolutionSummary,*Ev.UnresolvedPenaltySummary,*Ev.FollowUpEventType,*Ev.FollowUpTitle,Ev.FollowUpSeverityDelta,Ev.Choices.Num()); for(const FDemocracyEventChoiceState& Ch:Ev.Choices){ Out += FString::Printf(TEXT("|ch=%s,%s,%s,%s,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d"),*Ch.ChoiceId,*Ch.Label,*Ch.Description,*Ch.ConsequencePreview,Ch.ApprovalDelta,Ch.StabilityDelta,Ch.UnrestDelta,Ch.TreasuryDelta,Ch.EconomicDelta,Ch.DiplomacyDelta,Ch.MilitaryDelta,Ch.InfrastructureDelta,Ch.EnvironmentDelta,Ch.FoodDelta,Ch.WaterDelta,Ch.GasOilDelta,Ch.WoodDelta,Ch.MetalsDelta,Ch.AssassinationRiskDelta,Ch.InvasionRiskDelta); } }

        const FDemocracyDemographicsState& D=S.Demographics;
        Out += FString::Printf(TEXT("|demo=%d,%d,%d,%d,%d,%d,%d"),D.TotalPopulationThousands,D.AverageGroupApproval,D.AverageRegionalApproval,D.NationalNeedsPressure,D.DemographicUnrestPressure,D.CitizenGroups.Num(),D.Regions.Num()); AppendStringArraySignature(Out,TEXT("demoSources"),D.NationalUnrestSources);
        for(const FDemocracyCitizenGroupState& G:D.CitizenGroups){ Out += FString::Printf(TEXT("|grp=%s,%d,%d,%d,%d,%d,%d,%d,%d"),*G.GroupName,G.PopulationShare,G.Approval,G.NeedFood,G.NeedWater,G.NeedJobs,G.NeedSecurity,G.NeedHealthcare,G.UnrestPressure); AppendStringArraySignature(Out,TEXT("grpSrc"),G.UnrestSources); }
        for(const FDemocracyRegionState& R:D.Regions){ Out += FString::Printf(TEXT("|reg=%s,%s,%d,%d,%d,%d,%d,%d,%d,%d,%d"),*R.RegionName,*R.Climate,R.PopulationShare,R.Approval,R.Stability,R.Unrest,R.FoodAccess,R.WaterAccess,R.Jobs,R.Security,R.Infrastructure); AppendStringArraySignature(Out,TEXT("regSrc"),R.UnrestSources); }

        const FDemocracyEconomyBudgetState& B=S.EconomyBudget;
        Out += FString::Printf(TEXT("|budget=%d,%s,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%s,%s,%s"),B.TaxRate,*B.TaxPolicy,B.PublicServicesSpending,B.InfrastructureSpending,B.DefenseSpending,B.Debt,B.Income,B.Expenses,B.Deficit,B.Inflation,B.PublicServices,B.ProductionEfficiency,B.DebtCapacity,B.SpendingLimit,B.CreditStress,B.bSpendingLimited?1:0,*B.SpendingPosture,*B.BudgetConstraintStatus,*B.LastBudgetSummary);
        const FDemocracyResourceProductionChainState& RC=S.ResourceChains;
        Out += FString::Printf(TEXT("|chains=%d,%d,%d,%s,%d"),RC.TotalShortagePressure,RC.TradeBalance,RC.LastUpdatedTurn,*RC.Summary,RC.Chains.Num());
        for(const FDemocracyResourceChainEntry& CE:RC.Chains){ Out += FString::Printf(TEXT("|chain=%s,%d,%d,%d,%d,%d,%d,%d,%d,%d,%s,%s"),*CE.ResourceName,CE.Production,CE.Consumption,CE.Imports,CE.Exports,CE.Reserve,CE.ReserveTarget,CE.Shortage,CE.Surplus,CE.StrategicValue,*CE.Role,*CE.Status); AppendStringArraySignature(Out,TEXT("chainDrivers"),CE.Drivers); }

        const FDemocracyDepartmentSystemState& DS=S.Departments;
        Out += FString::Printf(TEXT("|depts=%d,%d,%s,%d"),DS.LastUpdatedTurn,DS.Coordination,*DS.Summary,DS.Departments.Num());
        for(const FDemocracyDepartmentState& Dept:DS.Departments){ Out += FString::Printf(TEXT("|dept=%s,%s,%s,%d,%d,%d,%d,%d,%s,%s,%s"),*Dept.DepartmentName,*Dept.MinisterTitle,*Dept.Domain,Dept.BudgetShare,Dept.Staffing,Dept.Effectiveness,Dept.PublicTrust,Dept.Priority,*Dept.CurrentAction,*Dept.PolicyInterface,*Dept.AdvisorySummary); AppendStringArraySignature(Out,TEXT("deptEffects"),Dept.ActionEffects); }
        const FDemocracyApprovalStabilityModelState& AS=S.ApprovalStability;
        Out += FString::Printf(TEXT("|approval=%d,%d,%d,%d,%s,%d"),AS.NetApprovalPressure,AS.NetUnrestPressure,AS.NetStabilityPressure,AS.LastUpdatedTurn,*AS.Summary,AS.Causes.Num());
        for(const FDemocracyApprovalCauseState& Cause:AS.Causes){ Out += FString::Printf(TEXT("|cause=%s,%s,%d,%d,%d,%d,%s,%s"),*Cause.CauseName,*Cause.Category,Cause.ApprovalImpact,Cause.UnrestImpact,Cause.StabilityImpact,Cause.Severity,*Cause.SourceMetric,*Cause.CurrentStatus); AppendStringArraySignature(Out,TEXT("causeResponses"),Cause.SuggestedResponses); }

        const FDemocracyPressOfficeState& P=S.PressOffice;
        Out += FString::Printf(TEXT("|press=%d,%d,%d,%d,%d,%d,%s,%d"),P.Credibility,P.ConsecutiveEmptyAnnouncements,P.ConsecutiveFalseAnnouncements,P.TotalAnnouncements,P.LastUpdatedTurn,P.MaxRecords,*P.LastAnnouncementSummary,P.Records.Num());
        for(const FDemocracyPressReleaseRecordState& PR:P.Records){ Out += FString::Printf(TEXT("|pr=%d,%s,%s,%d,%d,%d,%d,%d,%d,%d,%s"),PR.Turn,*PR.AnnouncementType,*PR.MessageQuality,PR.bTruthful?1:0,PR.ApprovalDelta,PR.StabilityDelta,PR.DiplomacyDelta,PR.UnrestDelta,PR.CredibilityDelta,PR.CredibilityAfter,*PR.Summary); }
        const FDemocracyMeetingSystemState& M=S.MeetingSystem;
        Out += FString::Printf(TEXT("|meet=%d,%d,%d,%d,%d,%s,%d"),M.TotalMeetings,M.AdvisorCoordination,M.ForeignTrust,M.LastUpdatedTurn,M.MaxRecords,*M.LastMeetingSummary,M.Records.Num());
        for(const FDemocracyMeetingRecordState& MR:M.Records){ Out += FString::Printf(TEXT("|mr=%d,%s,%s,%s,%s,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d"),MR.Turn,*MR.MeetingType,*MR.ParticipantName,*MR.AgendaItem,*MR.OutcomeSummary,MR.ApprovalDelta,MR.StabilityDelta,MR.UnrestDelta,MR.DiplomacyDelta,MR.TreasuryDelta,MR.EconomyDelta,MR.MilitaryDelta,MR.InfrastructureDelta,MR.AdvisorCoordinationDelta,MR.ForeignTrustDelta); }

        const FDemocracyDevelopmentSystemState& Dev=S.DevelopmentSystem;
        Out += FString::Printf(TEXT("|dev=%s,%d,%d,%s,%d"),*Dev.ActiveFocus,Dev.DevelopmentPoints,Dev.LastUpdatedTurn,*Dev.Summary,Dev.Tracks.Num());
        for(const FDemocracyDevelopmentTrackState& T:Dev.Tracks){ Out += FString::Printf(TEXT("|track=%s,%s,%d,%d,%d,%d,%d,%d,%d,%s,%s"),*T.TrackName,*T.FocusArea,T.Level,T.Progress,T.ProgressTarget,T.TreasuryCost,T.WoodCost,T.MetalsCost,T.FuelCost,*T.CurrentProject,*T.StrategicBenefit); AppendStringArraySignature(Out,TEXT("trackUnlocks"),T.Unlocks); }
        const FDemocracyDecisionHistoryState& H=S.DecisionHistory;
        Out += FString::Printf(TEXT("|hist=%d,%d,%s,%d"),H.LastUpdatedTurn,H.MaxRecords,*H.Summary,H.Records.Num());
        for(const FDemocracyDecisionRecordState& DR:H.Records){ Out += FString::Printf(TEXT("|decision=%d,%s,%s,%s,%s,%d,%d,%d,%d,%d,%d,%d,%s"),DR.Turn,*DR.Category,*DR.DecisionTitle,*DR.DecisionDetail,*DR.ConsequenceSummary,DR.ApprovalAfter,DR.StabilityAfter,DR.UnrestAfter,DR.TreasuryAfter,DR.EconomyAfter,DR.MilitaryAfter,DR.Severity,*DR.TimestampUtc); AppendStringArraySignature(Out,TEXT("decisionTags"),DR.Tags); }

        const FDemocracyWorldMapState& W=S.WorldMap;
        Out += FString::Printf(TEXT("|world=%d,%d,%d,%d,%s,%d"),W.ContinentCount,W.TotalCountryCount,W.DemocraticAllyCount,W.NonDemocraticCountryCount,*W.GenerationRule,W.Continents.Num());
        for(const FDemocracyContinentState& Cont:W.Continents){ Out += FString::Printf(TEXT("|cont=%s,%s,%d,%d"),*Cont.ContinentName,*Cont.Climate,Cont.CountryCount,Cont.Countries.Num()); for(const FDemocracyGeneratedCountryState& GC:Cont.Countries){ Out += FString::Printf(TEXT("|gc=%s,%s,%s,%s,%s,%d,%d,%d,%d"),*GC.CountryName,*GC.ContinentName,*GC.Climate,*GC.PoliticalType,*GC.DiplomaticAlignment,GC.PowerScore,GC.Stability,GC.BorderPressure,GC.bAlliedWithPlayer?1:0); } }
        const FDemocracyDiplomacyMatrixState& DM=S.DiplomacyMatrix;
        Out += FString::Printf(TEXT("|diplo=%d,%d,%d,%d,%d,%d,%d,%d,%d,%s,%d"),DM.LastUpdatedTurn,DM.AllyCount,DM.NeutralCount,DM.RivalCount,DM.HostileCount,DM.TradePartnerCount,DM.SanctionsCount,DM.TreatyCount,DM.AverageBorderTension,*DM.Summary,DM.Relationships.Num());
        for(const FDemocracyDiplomacyRelationshipState& Rel:DM.Relationships){ Out += FString::Printf(TEXT("|rel=%s,%s,%s,%s,%d,%d,%s,%d,%d,%d,%d"),*Rel.CountryName,*Rel.ContinentName,*Rel.GovernmentType,*Rel.RelationshipStatus,Rel.bTradePartner?1:0,Rel.bSanctionsActive?1:0,*Rel.TreatyStatus,Rel.BorderTension,Rel.Trust,Rel.TradeValue,Rel.LastChangedTurn); AppendStringArraySignature(Out,TEXT("relTreaties"),Rel.ActiveTreaties); AppendStringArraySignature(Out,TEXT("relNotes"),Rel.Notes); }
        const FDemocracyRtsWorldState& RW=S.RtsWorld;
        Out += FString::Printf(TEXT("|rts=%d,%d,%d,%d,%d"),RW.SimulationSecond,RW.ControlledTerritories,RW.BorderTerritories,RW.KnownRivalCountries,RW.Rivals.Num()); AppendStringArraySignature(Out,TEXT("rtsLayers"),RW.ActiveStrategicLayers);
        for(const FDemocracyRivalCountryState& Rival:RW.Rivals){ Out += FString::Printf(TEXT("|rival=%s,%s,%s,%d,%d,%d"),*Rival.CountryName,*Rival.Temperament,*Rival.RelationToPlayer,Rival.PowerScore,Rival.BorderPressure,Rival.TradeValue); }
        const FDemocracyRtsBackflowState& BF=RW.Backflow;
        Out += FString::Printf(TEXT("|rtsBackflow=%d,%d,%d,%d,%d,%d,%d,%d,%s,%d,%d"),BF.LastAppliedTurn,BF.PendingOutcomeCount,BF.TotalTerritoryDelta,BF.TotalCasualties,BF.WarFatigue,BF.ResourceDisruptionPressure,BF.BudgetStrainPressure,BF.DiplomaticDamagePressure,*BF.LastOutcomeSummary,BF.PendingOutcomes.Num(),BF.OutcomeHistory.Num());
        for(const FDemocracyRtsOutcomeState& RO:BF.PendingOutcomes){ Out += FString::Printf(TEXT("|pendingRts=%d,%s,%s,%s,%s,%d,%d,%d,%d,%d,%d,%d,%d,%d,%s"),RO.Turn,*RO.OutcomeId,*RO.ConflictName,*RO.OpponentCountry,*RO.OutcomeType,RO.TerritoryDelta,RO.Casualties,RO.ResourceDisruption,RO.WarFatigueDelta,RO.DiplomaticDamage,RO.StabilityDelta,RO.InvasionRiskDelta,RO.BudgetStrain,RO.bAppliedToSimulation?1:0,*RO.Summary); AppendStringArraySignature(Out,TEXT("pendingRtsTags"),RO.ConsequenceTags); }
        for(const FDemocracyRtsOutcomeState& RO:BF.OutcomeHistory){ Out += FString::Printf(TEXT("|histRts=%d,%s,%s,%s,%s,%d,%d,%d,%d,%d,%d,%d,%d,%d,%s"),RO.Turn,*RO.OutcomeId,*RO.ConflictName,*RO.OpponentCountry,*RO.OutcomeType,RO.TerritoryDelta,RO.Casualties,RO.ResourceDisruption,RO.WarFatigueDelta,RO.DiplomaticDamage,RO.StabilityDelta,RO.InvasionRiskDelta,RO.BudgetStrain,RO.bAppliedToSimulation?1:0,*RO.Summary); AppendStringArraySignature(Out,TEXT("histRtsTags"),RO.ConsequenceTags); }
        const FDemocracyMapOwnershipState& Own=RW.Ownership;
        Out += FString::Printf(TEXT("|own=%d,%d,%d,%d,%d,%d,%s,%s,%d,%d,%d"),Own.LastUpdatedTurn,Own.TotalCountries,Own.TotalProvinces,Own.PlayerControlledProvinces,Own.ContestedProvinces,Own.BorderProvinceCount,*Own.PlayerCountryName,*Own.Summary,Own.Provinces.Num(),Own.Countries.Num(),Own.Continents.Num());
        for(const FDemocracyProvinceOwnershipState& ProvinceOwnership:Own.Provinces){ Out += FString::Printf(TEXT("|prov=%s,%s,%s,%s,%s,%s,%s,%s,%s,%d,%d,%d,%d,%d,%d"),*ProvinceOwnership.ProvinceId,*ProvinceOwnership.ProvinceName,*ProvinceOwnership.ContinentName,*ProvinceOwnership.OriginalCountryName,*ProvinceOwnership.CurrentOwnerCountryName,*ProvinceOwnership.CurrentControllerCountryName,*ProvinceOwnership.GovernmentType,*ProvinceOwnership.Climate,*ProvinceOwnership.ResourceFocus,ProvinceOwnership.StrategicValue,ProvinceOwnership.Stability,ProvinceOwnership.Unrest,ProvinceOwnership.bPlayerControlled?1:0,ProvinceOwnership.bBorderProvince?1:0,ProvinceOwnership.LastChangedTurn); }
        for(const FDemocracyCountryOwnershipState& CountryOwnership:Own.Countries){ Out += FString::Printf(TEXT("|ownCountry=%s,%s,%s,%d,%d,%d,%d,%d,%d,%d,%d,%d"),*CountryOwnership.CountryName,*CountryOwnership.ContinentName,*CountryOwnership.GovernmentType,CountryOwnership.TotalProvinces,CountryOwnership.ControlledProvinces,CountryOwnership.OccupiedProvinces,CountryOwnership.LostProvinces,CountryOwnership.BorderProvinces,CountryOwnership.ResourceBase,CountryOwnership.MilitaryValue,CountryOwnership.bPlayerCountry?1:0,CountryOwnership.bCapitalControlled?1:0); AppendStringArraySignature(Out,TEXT("ownCountryProvinces"),CountryOwnership.ProvinceIds); }
        for(const FDemocracyContinentOwnershipState& ContinentOwnership:Own.Continents){ Out += FString::Printf(TEXT("|ownContinent=%s,%s,%d,%d,%d,%d"),*ContinentOwnership.ContinentName,*ContinentOwnership.Climate,ContinentOwnership.CountryCount,ContinentOwnership.ProvinceCount,ContinentOwnership.PlayerControlledProvinces,ContinentOwnership.ContestedProvinces); AppendStringArraySignature(Out,TEXT("ownContinentCountries"),ContinentOwnership.CountryNames); }
        return Out;
    }

    bool ValidateRuntimeStateRoundTrip(const FDemocracySimulationState& State,FString& Err)
    {
        FString RuntimeJson=State.ToJson(2);
        TSharedPtr<FJsonObject> StateObj;
        const TSharedRef<TJsonReader<>> Reader=TJsonReaderFactory<>::Create(RuntimeJson);
        if(!FJsonSerializer::Deserialize(Reader,StateObj)||!StateObj.IsValid()){ Err=TEXT("Persistent runtime state could not be parsed after serialization."); return false; }
        const TCHAR* RequiredObjects[]={TEXT("playerCountry"),TEXT("failureRisk"),TEXT("invasionRisk"),TEXT("advisorSystem"),TEXT("eventSystem"),TEXT("demographics"),TEXT("economyBudget"),TEXT("resourceChains"),TEXT("departments"),TEXT("approvalStability"),TEXT("pressOffice"),TEXT("meetingSystem"),TEXT("developmentSystem"),TEXT("decisionHistory"),TEXT("worldMap"),TEXT("diplomacyMatrix"),TEXT("rtsWorld"),TEXT("commandAuthority"),TEXT("objectiveState")};
        for(const TCHAR* FieldName:RequiredObjects){ if(!Obj(StateObj,FieldName).IsValid()){ Err=FString::Printf(TEXT("Persistent runtime state is missing serialized system object: %s"),FieldName); return false; } }
        FDemocracySimulationState Reloaded=ParseState(StateObj);
        const FString Before=PersistentRuntimeSignature(State);
        const FString After=PersistentRuntimeSignature(Reloaded);
        if(!Before.Equals(After,ESearchCase::CaseSensitive)){ Err=TEXT("Persistent runtime state round-trip mismatch. A simulation system changed during save/load serialization."); return false; }
        return true;
    }
    bool BuildUpdated(FDemocracyLoadedSaveState& L,const FString& Kind,FString& Out,FString& Err){ TSharedPtr<FJsonObject> Root; if(!LoadRootFallback(L.SavePath,Root,Err)) return false; TSharedPtr<FJsonObject> StateObj; const TSharedRef<TJsonReader<>> SR=TJsonReaderFactory<>::Create(L.RuntimeState.ToJson(2)); if(!FJsonSerializer::Deserialize(SR,StateObj)||!StateObj.IsValid()){ Err=TEXT("Runtime state could not be converted to JSON for saving."); return false; } if(!ValidateRuntimeStateRoundTrip(L.RuntimeState,Err)) return false; L.LastPlayedAtUtc=FDateTime::UtcNow().ToIso8601(); Root->SetNumberField(TEXT("formatVersion"),FMath::Max(1,Int(Root,TEXT("formatVersion"),1))); Root->SetNumberField(TEXT("saveVersion"),Int(Root,TEXT("saveVersion"),0)+1); Root->SetStringField(TEXT("lastPlayedAtUtc"),L.LastPlayedAtUtc); Root->SetStringField(TEXT("lastSaveKind"),Kind); Root->SetStringField(Kind.Equals(TEXT("Autosave"),ESearchCase::IgnoreCase)?TEXT("lastAutosaveAtUtc"):TEXT("lastManualSaveAtUtc"),L.LastPlayedAtUtc); Root->SetObjectField(TEXT("currentGameState"),StateObj); TSharedPtr<FJsonObject> Prot=MakeShared<FJsonObject>(); Prot->SetStringField(TEXT("autosavePath"),AutoPath(L.SavePath)); Prot->SetStringField(TEXT("backup1Path"),BakPath(L.SavePath,1)); Prot->SetStringField(TEXT("backup2Path"),BakPath(L.SavePath,2)); Prot->SetNumberField(TEXT("redundantCopies"),2); Root->SetObjectField(TEXT("saveProtection"),Prot); TSharedPtr<FJsonObject> Progress=MakeShared<FJsonObject>(); Progress->SetNumberField(TEXT("turn"),L.RuntimeState.Turn); Progress->SetStringField(TEXT("phase"),L.RuntimeState.Phase); Progress->SetNumberField(TEXT("simulationSecond"),L.RuntimeState.RtsWorld.SimulationSecond); Progress->SetBoolField(TEXT("paused"),L.RuntimeState.bPaused); Root->SetObjectField(TEXT("progress"),Progress); const TSharedRef<TJsonWriter<>> W=TJsonWriterFactory<>::Create(&Out); if(!FJsonSerializer::Serialize(Root.ToSharedRef(),W)){ Err=TEXT("Could not serialize updated save JSON."); return false; } return true; }
}

FString FDemocracyLoadedSaveState::ToSummaryText() const{ return FString::Printf(TEXT("%s | %s | %s | turn %d | continents %d | countries %d | allies %d"),*StateName,*Difficulty,*Climate,RuntimeState.Turn,RuntimeState.WorldMap.Continents.Num(),RuntimeState.WorldMap.TotalCountryCount,RuntimeState.WorldMap.DemocraticAllyCount); }

bool FDemocracySaveGameRuntime::LoadSinglePlayerSave(const FString& SavePath,FDemocracyLoadedSaveState& Out,FString& Err){ TSharedPtr<FJsonObject> Root; if(!LoadRoot(SavePath,Root,Err)) return false; TSharedPtr<FJsonObject> Cur=Obj(Root,TEXT("currentGameState")); if(!Cur.IsValid()) Cur=Obj(Root,TEXT("initialGameState")); Out=FDemocracyLoadedSaveState(); Out.FormatVersion=Int(Root,TEXT("formatVersion")); Out.SaveId=Str(Root,TEXT("saveId")); Out.StateName=Str(Root,TEXT("stateName")); Out.Mode=Str(Root,TEXT("mode")); Out.Difficulty=Str(Root,TEXT("difficulty")); Out.Climate=Str(Root,TEXT("climate")); Out.LeaderGender=Str(Root,TEXT("leaderGender")); Out.AddressTitle=Str(Root,TEXT("addressTitle")); Out.CreatedAtUtc=Str(Root,TEXT("createdAtUtc")); Out.LastPlayedAtUtc=Str(Root,TEXT("lastPlayedAtUtc")); Out.SavePath=SavePath; Out.RuntimeState=ParseState(Cur); if(Out.StateName.IsEmpty()) Out.StateName=Out.RuntimeState.PlayerCountry.CountryName; UE_LOG(LogTemp,Log,TEXT("Loaded Democracy save into runtime: %s"),*Out.ToSummaryText()); return true; }

bool FDemocracySaveGameRuntime::LoadSinglePlayerSaveWithFallback(const FString& SavePath,FDemocracyLoadedSaveState& Out,FString& Err){ TArray<FString> Errors; for(const FString& C:Candidates(SavePath,true)){ if(!FPaths::FileExists(C)) continue; FString E; if(LoadSinglePlayerSave(C,Out,E)){ if(!C.Equals(SavePath,ESearchCase::IgnoreCase)){ Out.SavePath=SavePath; Err=FString::Printf(TEXT("Loaded protected backup because the primary save was unavailable or invalid: %s"),*C); UE_LOG(LogTemp,Warning,TEXT("Recovered Democracy save from protected backup: %s"),*C); } return true; } Errors.Add(E); } Err=Errors.Num()?FString::Join(Errors,TEXT("\n")):FString::Printf(TEXT("No readable save, autosave, or backup exists for %s"),*SavePath); return false; }

bool FDemocracySaveGameRuntime::SaveSinglePlayerRuntimeState(FDemocracyLoadedSaveState& L,FString& Err){ if(L.SavePath.IsEmpty()){ Err=TEXT("No save path is available for the loaded state."); return false; } FString C; if(!BuildUpdated(L,TEXT("Manual"),C,Err)) return false; if(!WriteProtected(L.SavePath,C,true,Err)) return false; UE_LOG(LogTemp,Log,TEXT("Saved Democracy runtime state with protected backups: %s"),*L.SavePath); return true; }

bool FDemocracySaveGameRuntime::SaveSinglePlayerAutosave(FDemocracyLoadedSaveState& L,FString& Err){ if(L.SavePath.IsEmpty()){ Err=TEXT("No save path is available for autosave."); return false; } FString C; if(!BuildUpdated(L,TEXT("Autosave"),C,Err)) return false; const FString A=AutoPath(L.SavePath); if(!WriteProtected(A,C,true,Err)) return false; UE_LOG(LogTemp,Log,TEXT("Autosaved Democracy runtime state with protected backups: %s"),*A); return true; }

bool FDemocracySaveGameRuntime::GetProtectedReloadSavePath(const FString& SavePath,FString& OutReloadPath,FString& Err){ for(const FString& C:Candidates(SavePath,false)){ if(ValidSave(C)){ OutReloadPath=C; return true; } } Err=FString::Printf(TEXT("No valid protected reload save exists for %s"),*SavePath); return false; }
bool FDemocracySaveGameRuntime::RunAutosaveRecoverySelfTest(FString& OutReport, FString& OutError)
{
    const FString TestRoot = FPaths::Combine(FPaths::ProjectSavedDir(), TEXT("DemocracySaveRecoveryTests"), FGuid::NewGuid().ToString(EGuidFormats::Digits));
    const FString PrimaryPath = FPaths::Combine(TestRoot, TEXT("RecoveryTest.democracy"));
    const FString AutosavePath = PrimaryPath + TEXT(".autosave");
    const FString AutosaveBak1Path = AutosavePath + TEXT(".bak1");
    const FString AutosaveBak2Path = AutosavePath + TEXT(".bak2");

    auto Cleanup = [&TestRoot]()
    {
        IFileManager::Get().DeleteDirectory(*TestRoot, false, true);
    };

    auto Fail = [&OutError, &Cleanup](const FString& Message) -> bool
    {
        OutError = Message;
        Cleanup();
        return false;
    };

    if (!IFileManager::Get().MakeDirectory(*TestRoot, true))
    {
        return Fail(FString::Printf(TEXT("Could not create autosave recovery test directory: %s"), *TestRoot));
    }

    FDemocracyLoadedSaveState TestSave;
    TestSave.FormatVersion = 1;
    TestSave.SaveId = TEXT("AutosaveRecoverySelfTest");
    TestSave.StateName = TEXT("Autosave Recovery Self Test");
    TestSave.Mode = TEXT("SinglePlayer");
    TestSave.Difficulty = TEXT("Normal");
    TestSave.Climate = TEXT("Middle Moderate");
    TestSave.LeaderGender = TEXT("Female");
    TestSave.AddressTitle = TEXT("Miss President");
    TestSave.CreatedAtUtc = FDateTime::UtcNow().ToIso8601();
    TestSave.LastPlayedAtUtc = TestSave.CreatedAtUtc;
    TestSave.SavePath = PrimaryPath;
    TestSave.RuntimeState = FDemocracySimulationState();
    TestSave.RuntimeState.Turn = 1;
    TestSave.RuntimeState.Phase = TEXT("Protected Baseline");
    TestSave.RuntimeState.bPaused = true;
    TestSave.RuntimeState.PlayerCountry.CountryName = TestSave.StateName;
    TestSave.RuntimeState.PlayerCountry.Difficulty = TestSave.Difficulty;
    TestSave.RuntimeState.PlayerCountry.Climate = TestSave.Climate;
    TestSave.RuntimeState.PlayerCountry.LeaderGender = TestSave.LeaderGender;
    TestSave.RuntimeState.PlayerCountry.AddressTitle = TestSave.AddressTitle;

    const FString BaselineJson = FString::Printf(
        TEXT("{\n  \"formatVersion\": 1,\n  \"saveVersion\": 1,\n  \"saveId\": \"%s\",\n  \"stateName\": \"%s\",\n  \"mode\": \"SinglePlayer\",\n  \"difficulty\": \"%s\",\n  \"climate\": \"%s\",\n  \"leaderGender\": \"%s\",\n  \"addressTitle\": \"%s\",\n  \"createdAtUtc\": \"%s\",\n  \"lastPlayedAtUtc\": \"%s\",\n  \"currentGameState\": %s\n}"),
        *TestSave.SaveId,
        *TestSave.StateName,
        *TestSave.Difficulty,
        *TestSave.Climate,
        *TestSave.LeaderGender,
        *TestSave.AddressTitle,
        *TestSave.CreatedAtUtc,
        *TestSave.LastPlayedAtUtc,
        *TestSave.RuntimeState.ToJson(2));

    if (!FFileHelper::SaveStringToFile(BaselineJson, *PrimaryPath))
    {
        return Fail(FString::Printf(TEXT("Could not write autosave recovery baseline save: %s"), *PrimaryPath));
    }

    FString SaveError;
    for (int32 Turn = 2; Turn <= 4; ++Turn)
    {
        TestSave.RuntimeState.Turn = Turn;
        TestSave.RuntimeState.Phase = FString::Printf(TEXT("Autosave Recovery Turn %d"), Turn);
        if (!SaveSinglePlayerAutosave(TestSave, SaveError))
        {
            return Fail(FString::Printf(TEXT("Autosave rotation write failed on turn %d: %s"), Turn, *SaveError));
        }
    }

    auto LoadTurn = [](const FString& Path, int32& OutTurn, FString& Error) -> bool
    {
        FDemocracyLoadedSaveState Loaded;
        if (!FDemocracySaveGameRuntime::LoadSinglePlayerSave(Path, Loaded, Error))
        {
            return false;
        }
        OutTurn = Loaded.RuntimeState.Turn;
        return true;
    };

    int32 AutosaveTurn = 0;
    int32 Bak1Turn = 0;
    int32 Bak2Turn = 0;
    if (!FPaths::FileExists(AutosavePath) || !FPaths::FileExists(AutosaveBak1Path) || !FPaths::FileExists(AutosaveBak2Path))
    {
        return Fail(FString::Printf(TEXT("Autosave rotation did not create expected files. autosave=%d bak1=%d bak2=%d"), FPaths::FileExists(AutosavePath) ? 1 : 0, FPaths::FileExists(AutosaveBak1Path) ? 1 : 0, FPaths::FileExists(AutosaveBak2Path) ? 1 : 0));
    }
    if (!LoadTurn(AutosavePath, AutosaveTurn, SaveError) || !LoadTurn(AutosaveBak1Path, Bak1Turn, SaveError) || !LoadTurn(AutosaveBak2Path, Bak2Turn, SaveError))
    {
        return Fail(FString::Printf(TEXT("Could not load rotated autosave files: %s"), *SaveError));
    }
    if (AutosaveTurn != 4 || Bak1Turn != 3 || Bak2Turn != 2)
    {
        return Fail(FString::Printf(TEXT("Autosave rotation order invalid. autosave turn %d, bak1 turn %d, bak2 turn %d; expected 4, 3, 2."), AutosaveTurn, Bak1Turn, Bak2Turn));
    }

    TestSave.RuntimeState.Turn = 99;
    TestSave.RuntimeState.Phase = TEXT("Failed State In Memory Only");
    FString ReloadPath;
    if (!GetProtectedReloadSavePath(PrimaryPath, ReloadPath, SaveError))
    {
        return Fail(FString::Printf(TEXT("Protected reload path was not available after autosave rotation: %s"), *SaveError));
    }
    int32 ReloadTurn = 0;
    if (!LoadTurn(ReloadPath, ReloadTurn, SaveError))
    {
        return Fail(FString::Printf(TEXT("Could not load protected reload source %s: %s"), *ReloadPath, *SaveError));
    }
    if (ReloadTurn == TestSave.RuntimeState.Turn || ReloadTurn != 4)
    {
        return Fail(FString::Printf(TEXT("Protected reload selected the wrong state. Reload path %s turn %d, failed in-memory turn %d; expected protected turn 4."), *ReloadPath, ReloadTurn, TestSave.RuntimeState.Turn));
    }

    if (!FFileHelper::SaveStringToFile(TEXT("{ corrupted autosave"), *AutosavePath))
    {
        return Fail(FString::Printf(TEXT("Could not corrupt disposable autosave for fallback test: %s"), *AutosavePath));
    }
    FString FallbackReloadPath;
    if (!GetProtectedReloadSavePath(PrimaryPath, FallbackReloadPath, SaveError))
    {
        return Fail(FString::Printf(TEXT("Protected reload fallback was not available after corrupting newest autosave: %s"), *SaveError));
    }
    int32 FallbackTurn = 0;
    if (!LoadTurn(FallbackReloadPath, FallbackTurn, SaveError))
    {
        return Fail(FString::Printf(TEXT("Could not load fallback protected reload source %s: %s"), *FallbackReloadPath, *SaveError));
    }
    if (!FallbackReloadPath.Equals(AutosaveBak1Path, ESearchCase::IgnoreCase) || FallbackTurn != 3)
    {
        return Fail(FString::Printf(TEXT("Protected reload fallback selected wrong source. Path %s turn %d; expected %s turn 3."), *FallbackReloadPath, FallbackTurn, *AutosaveBak1Path));
    }

    OutReport = FString::Printf(TEXT("Autosave recovery self-test passed. Rotation autosave/bak1/bak2 turns = %d/%d/%d. Failed in-memory turn 99 was not saved; protected reload selected %s turn %d. Corrupted newest autosave fell back to %s turn %d."), AutosaveTurn, Bak1Turn, Bak2Turn, *ReloadPath, ReloadTurn, *FallbackReloadPath, FallbackTurn);
    Cleanup();
    return true;
}


