#include "DemocracySaveGameRuntime.h"

#include "Dom/JsonObject.h"
#include "HAL/FileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "Serialization/JsonWriter.h"

namespace
{
    FString Str(const TSharedPtr<FJsonObject>& O,const TCHAR* K,const FString& D=TEXT("")){ if(!O.IsValid()) return D; FString V; return O->TryGetStringField(K,V)?V:D; }
    int32 Int(const TSharedPtr<FJsonObject>& O,const TCHAR* K,int32 D=0){ if(!O.IsValid()) return D; int32 V=0; return O->TryGetNumberField(K,V)?V:D; }
    float Flt(const TSharedPtr<FJsonObject>& O,const TCHAR* K,float D=0.f){ if(!O.IsValid()) return D; double V=0; return O->TryGetNumberField(K,V)?static_cast<float>(V):D; }
    bool Bool(const TSharedPtr<FJsonObject>& O,const TCHAR* K,bool D=false){ if(!O.IsValid()) return D; bool V=false; return O->TryGetBoolField(K,V)?V:D; }
    TSharedPtr<FJsonObject> Obj(const TSharedPtr<FJsonObject>& O,const TCHAR* K){ const TSharedPtr<FJsonObject>* V=nullptr; return O.IsValid()&&O->TryGetObjectField(K,V)&&V?*V:nullptr; }
    TArray<FString> Strs(const TSharedPtr<FJsonObject>& O,const TCHAR* K){ TArray<FString> R; const TArray<TSharedPtr<FJsonValue>>* A=nullptr; if(O.IsValid()&&O->TryGetArrayField(K,A)&&A){ for(const auto& V:*A){ FString S; if(V.IsValid()&&V->TryGetString(S)) R.Add(S); } } return R; }
    template<typename T,typename F> void ObjArray(const TSharedPtr<FJsonObject>& O,const TCHAR* K,TArray<T>& Out,F Fn){ const TArray<TSharedPtr<FJsonValue>>* A=nullptr; if(O.IsValid()&&O->TryGetArrayField(K,A)&&A){ for(const auto& V:*A){ TSharedPtr<FJsonObject> VO=V.IsValid()?V->AsObject():nullptr; if(VO.IsValid()) Out.Add(Fn(VO)); } } }
    FString AutoPath(const FString& P){ return P+TEXT(".autosave"); }
    FString BakPath(const FString& P,int32 I){ return FString::Printf(TEXT("%s.bak%d"),*P,I); }
    TArray<FString> Candidates(const FString& P,bool PrimaryFirst){ TArray<FString> C; const FString A=AutoPath(P); if(PrimaryFirst){ C={P,A,BakPath(P,1),BakPath(A,1),BakPath(P,2),BakPath(A,2)}; } else { C={A,BakPath(A,1),BakPath(P,1),BakPath(A,2),BakPath(P,2),P}; } return C; }

    bool LoadRoot(const FString& P,TSharedPtr<FJsonObject>& Root,FString& Err)
    {
        FString S; if(!FFileHelper::LoadFileToString(S,*P)){ Err=FString::Printf(TEXT("Could not read save file: %s"),*P); return false; }
        const TSharedRef<TJsonReader<>> R=TJsonReaderFactory<>::Create(S); if(!FJsonSerializer::Deserialize(R,Root)||!Root.IsValid()){ Err=FString::Printf(TEXT("Save file is not valid JSON: %s"),*P); return false; }
        if(!Str(Root,TEXT("mode")).Equals(TEXT("SinglePlayer"),ESearchCase::IgnoreCase)){ Err=FString::Printf(TEXT("Save file is not a single-player save: %s"),*P); return false; }
        if(!Obj(Root,TEXT("currentGameState")).IsValid()&&!Obj(Root,TEXT("initialGameState")).IsValid()){ Err=FString::Printf(TEXT("Save file is missing game state data: %s"),*P); return false; }
        return true;
    }
    bool ValidSave(const FString& P){ if(!FPaths::FileExists(P)) return false; TSharedPtr<FJsonObject> R; FString E; return LoadRoot(P,R,E); }
    bool LoadRootFallback(const FString& P,TSharedPtr<FJsonObject>& R,FString& Err){ TArray<FString> Es; for(const FString& C:Candidates(P,true)){ if(!FPaths::FileExists(C)) continue; FString E; if(LoadRoot(C,R,E)) return true; Es.Add(E); } Err=Es.Num()?FString::Join(Es,TEXT("\n")):FString::Printf(TEXT("No readable save or backup file exists for %s"),*P); return false; }
    bool CopyIfExists(const FString& S,const FString& D,FString& E){ if(!FPaths::FileExists(S)) return true; FString C; if(!FFileHelper::LoadFileToString(C,*S)){ E=FString::Printf(TEXT("Could not read backup source: %s"),*S); return false; } if(!FFileHelper::SaveStringToFile(C,*D)){ E=FString::Printf(TEXT("Could not write backup file: %s"),*D); return false; } return true; }
    bool Rotate(const FString& P,FString& E){ if(!FPaths::FileExists(P)) return true; IFileManager::Get().Delete(*BakPath(P,2),false,true); return CopyIfExists(BakPath(P,1),BakPath(P,2),E)&&CopyIfExists(P,BakPath(P,1),E); }
    bool WriteProtected(const FString& P,const FString& C,bool bRotate,FString& E){ const FString T=P+TEXT(".tmp"); if(!FFileHelper::SaveStringToFile(C,*T)){ E=FString::Printf(TEXT("Could not write temporary save file: %s"),*T); return false; } if(!ValidSave(T)){ IFileManager::Get().Delete(*T,false,true); E=FString::Printf(TEXT("Temporary save failed validation: %s"),*T); return false; } if(bRotate&&!Rotate(P,E)){ IFileManager::Get().Delete(*T,false,true); return false; } if(!FFileHelper::SaveStringToFile(C,*P)){ IFileManager::Get().Delete(*T,false,true); E=FString::Printf(TEXT("Could not write updated save file: %s"),*P); return false; } IFileManager::Get().Delete(*T,false,true); return true; }

    FDemocracyResourceInventory ParseResources(const TSharedPtr<FJsonObject>& O){ FDemocracyResourceInventory R; R.Food=Int(O,TEXT("food"),R.Food); R.GasOil=Int(O,TEXT("gasOil"),R.GasOil); R.Wood=Int(O,TEXT("wood"),R.Wood); R.Metals=Int(O,TEXT("metals"),R.Metals); R.Water=Int(O,TEXT("water"),R.Water); return R; }
    FDemocracyPolicyState ParsePolicies(const TSharedPtr<FJsonObject>& O){ FDemocracyPolicyState P; P.EconomicPolicy=Str(O,TEXT("economicPolicy"),P.EconomicPolicy); P.EnvironmentalPolicy=Str(O,TEXT("environmentalPolicy"),P.EnvironmentalPolicy); P.MilitaryPolicy=Str(O,TEXT("militaryPolicy"),P.MilitaryPolicy); P.DiplomacyPolicy=Str(O,TEXT("diplomacyPolicy"),P.DiplomacyPolicy); P.CivilPolicy=Str(O,TEXT("civilPolicy"),P.CivilPolicy); P.PolicyChangeCount=Int(O,TEXT("policyChangeCount"),P.PolicyChangeCount); P.LastPolicyChangeSummary=Str(O,TEXT("lastPolicyChangeSummary"),P.LastPolicyChangeSummary); P.ActivePolicyEffects=Strs(O,TEXT("activePolicyEffects")); return P; }
    FDemocracyCountryState ParseCountry(const TSharedPtr<FJsonObject>& O){ FDemocracyCountryState C; C.CountryName=Str(O,TEXT("countryName"),C.CountryName); C.LeaderGender=Str(O,TEXT("leaderGender"),C.LeaderGender); C.AddressTitle=Str(O,TEXT("addressTitle"),C.AddressTitle); C.Climate=Str(O,TEXT("climate"),C.Climate); C.Difficulty=Str(O,TEXT("difficulty"),C.Difficulty); C.CountrySize=Str(O,TEXT("countrySize"),C.CountrySize); C.CountrySizeScore=Int(O,TEXT("countrySizeScore"),C.CountrySizeScore); C.PublicApproval=Int(O,TEXT("publicApproval"),C.PublicApproval); C.Stability=Int(O,TEXT("stability"),C.Stability); C.Unrest=Int(O,TEXT("unrest"),C.Unrest); C.Treasury=Int(O,TEXT("treasury"),C.Treasury); C.EconomicHealth=Int(O,TEXT("economicHealth"),C.EconomicHealth); C.DiplomaticStanding=Int(O,TEXT("diplomaticStanding"),C.DiplomaticStanding); C.Technology=Int(O,TEXT("technology"),C.Technology); C.MilitaryReadiness=Int(O,TEXT("militaryReadiness"),C.MilitaryReadiness); C.Infrastructure=Int(O,TEXT("infrastructure"),C.Infrastructure); C.EnvironmentalHealth=Int(O,TEXT("environmentalHealth"),C.EnvironmentalHealth); C.Resources=ParseResources(Obj(O,TEXT("resources"))); C.Policies=ParsePolicies(Obj(O,TEXT("policies"))); return C; }
    FDemocracyFailureRiskState ParseFailure(const TSharedPtr<FJsonObject>& O){ FDemocracyFailureRiskState R; R.StabilityWarningThreshold=Int(O,TEXT("stabilityWarningThreshold"),R.StabilityWarningThreshold); R.StabilityCriticalThreshold=Int(O,TEXT("stabilityCriticalThreshold"),R.StabilityCriticalThreshold); R.UnrestWarningThreshold=Int(O,TEXT("unrestWarningThreshold"),R.UnrestWarningThreshold); R.UnrestCriticalThreshold=Int(O,TEXT("unrestCriticalThreshold"),R.UnrestCriticalThreshold); R.CurrentAssassinationRisk=Int(O,TEXT("currentAssassinationRisk"),R.CurrentAssassinationRisk); R.AssassinationRiskTrigger=Int(O,TEXT("assassinationRiskTrigger"),R.AssassinationRiskTrigger); R.WarningLevel=Str(O,TEXT("warningLevel"),R.WarningLevel); R.GameOverReason=Str(O,TEXT("gameOverReason"),R.GameOverReason); R.bGameOverOnAssassination=Bool(O,TEXT("gameOverOnAssassination"),R.bGameOverOnAssassination); R.ActiveUnrestCauses=Strs(O,TEXT("activeUnrestCauses")); R.AdvisorWarnings=Strs(O,TEXT("advisorWarnings")); R.RecoveryTips=Strs(O,TEXT("recoveryTips")); return R; }
    FDemocracyInvasionRiskState ParseInvasion(const TSharedPtr<FJsonObject>& O){ FDemocracyInvasionRiskState R; R.MilitaryReadinessWarningThreshold=Int(O,TEXT("militaryReadinessWarningThreshold"),R.MilitaryReadinessWarningThreshold); R.MilitaryReadinessCriticalThreshold=Int(O,TEXT("militaryReadinessCriticalThreshold"),R.MilitaryReadinessCriticalThreshold); R.BorderPressureWarningThreshold=Int(O,TEXT("borderPressureWarningThreshold"),R.BorderPressureWarningThreshold); R.BorderPressureCriticalThreshold=Int(O,TEXT("borderPressureCriticalThreshold"),R.BorderPressureCriticalThreshold); R.TerritorialLossWarningThreshold=Int(O,TEXT("territorialLossWarningThreshold"),R.TerritorialLossWarningThreshold); R.TerritorialLossCriticalThreshold=Int(O,TEXT("territorialLossCriticalThreshold"),R.TerritorialLossCriticalThreshold); R.CurrentInvasionRisk=Int(O,TEXT("currentInvasionRisk"),R.CurrentInvasionRisk); R.InvasionRiskTrigger=Int(O,TEXT("invasionRiskTrigger"),R.InvasionRiskTrigger); R.WarningLevel=Str(O,TEXT("warningLevel"),R.WarningLevel); R.GameOverReason=Str(O,TEXT("gameOverReason"),R.GameOverReason); R.bGameOverOnTakeover=Bool(O,TEXT("gameOverOnTakeover"),R.bGameOverOnTakeover); R.ActiveInvasionCauses=Strs(O,TEXT("activeInvasionCauses")); R.AdvisorWarnings=Strs(O,TEXT("advisorWarnings")); R.RecoveryTips=Strs(O,TEXT("recoveryTips")); return R; }    FDemocracyAdvisorReport ParseReport(const TSharedPtr<FJsonObject>& O){ FDemocracyAdvisorReport R; R.AdvisorName=Str(O,TEXT("advisorName"),R.AdvisorName); R.Category=Str(O,TEXT("category"),R.Category); R.IssueReport=Str(O,TEXT("issueReport"),R.IssueReport); R.Recommendation=Str(O,TEXT("recommendation"),R.Recommendation); R.Warning=Str(O,TEXT("warning"),R.Warning); R.TradeoffExplanation=Str(O,TEXT("tradeoffExplanation"),R.TradeoffExplanation); R.GuidanceLevel=Str(O,TEXT("guidanceLevel"),R.GuidanceLevel); R.Severity=Int(O,TEXT("severity"),R.Severity); return R; }
    FDemocracyAdvisorSystemState ParseAdvisor(const TSharedPtr<FJsonObject>& O){ FDemocracyAdvisorSystemState S; S.GuidanceLevel=Str(O,TEXT("guidanceLevel"),S.GuidanceLevel); S.AdvisorCount=Int(O,TEXT("advisorCount"),S.AdvisorCount); S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); ObjArray(O,TEXT("reports"),S.Reports,ParseReport); return S; }
    FDemocracyEventChoiceState ParseChoice(const TSharedPtr<FJsonObject>& O){ FDemocracyEventChoiceState C; C.ChoiceId=Str(O,TEXT("choiceId"),C.ChoiceId); C.Label=Str(O,TEXT("label"),C.Label); C.Description=Str(O,TEXT("description"),C.Description); C.ConsequencePreview=Str(O,TEXT("consequencePreview"),C.ConsequencePreview); C.ApprovalDelta=Int(O,TEXT("approvalDelta"),C.ApprovalDelta); C.StabilityDelta=Int(O,TEXT("stabilityDelta"),C.StabilityDelta); C.UnrestDelta=Int(O,TEXT("unrestDelta"),C.UnrestDelta); C.TreasuryDelta=Int(O,TEXT("treasuryDelta"),C.TreasuryDelta); C.EconomicDelta=Int(O,TEXT("economicDelta"),C.EconomicDelta); C.DiplomacyDelta=Int(O,TEXT("diplomacyDelta"),C.DiplomacyDelta); C.MilitaryDelta=Int(O,TEXT("militaryDelta"),C.MilitaryDelta); C.InfrastructureDelta=Int(O,TEXT("infrastructureDelta"),C.InfrastructureDelta); C.EnvironmentDelta=Int(O,TEXT("environmentDelta"),C.EnvironmentDelta); C.FoodDelta=Int(O,TEXT("foodDelta"),C.FoodDelta); C.WaterDelta=Int(O,TEXT("waterDelta"),C.WaterDelta); C.GasOilDelta=Int(O,TEXT("gasOilDelta"),C.GasOilDelta); C.WoodDelta=Int(O,TEXT("woodDelta"),C.WoodDelta); C.MetalsDelta=Int(O,TEXT("metalsDelta"),C.MetalsDelta); C.AssassinationRiskDelta=Int(O,TEXT("assassinationRiskDelta"),C.AssassinationRiskDelta); C.InvasionRiskDelta=Int(O,TEXT("invasionRiskDelta"),C.InvasionRiskDelta); return C; }
    FDemocracyActiveEventState ParseEvent(const TSharedPtr<FJsonObject>& O){ FDemocracyActiveEventState E; E.EventId=Str(O,TEXT("eventId"),E.EventId); E.EventType=Str(O,TEXT("eventType"),E.EventType); E.Title=Str(O,TEXT("title"),E.Title); E.Description=Str(O,TEXT("description"),E.Description); E.TriggerReason=Str(O,TEXT("triggerReason"),E.TriggerReason); E.CreatedTurn=Int(O,TEXT("createdTurn"),E.CreatedTurn); E.Severity=Int(O,TEXT("severity"),E.Severity); E.bTriggered=Bool(O,TEXT("triggered"),E.bTriggered); E.bResolved=Bool(O,TEXT("resolved"),E.bResolved); E.SelectedChoiceId=Str(O,TEXT("selectedChoiceId"),E.SelectedChoiceId); E.ResolutionSummary=Str(O,TEXT("resolutionSummary"),E.ResolutionSummary); ObjArray(O,TEXT("choices"),E.Choices,ParseChoice); return E; }
    FDemocracyEventSystemState ParseEvents(const TSharedPtr<FJsonObject>& O){ FDemocracyEventSystemState S; S.LastEventTurn=Int(O,TEXT("lastEventTurn"),S.LastEventTurn); S.EventCounter=Int(O,TEXT("eventCounter"),S.EventCounter); S.ActiveEventLimit=Int(O,TEXT("activeEventLimit"),S.ActiveEventLimit); S.EventHistory=Strs(O,TEXT("eventHistory")); ObjArray(O,TEXT("activeEvents"),S.ActiveEvents,ParseEvent); return S; }
    FDemocracyCitizenGroupState ParseGroup(const TSharedPtr<FJsonObject>& O){ FDemocracyCitizenGroupState G; G.GroupName=Str(O,TEXT("groupName"),G.GroupName); G.PopulationShare=Int(O,TEXT("populationShare"),G.PopulationShare); G.Approval=Int(O,TEXT("approval"),G.Approval); G.NeedFood=Int(O,TEXT("needFood"),G.NeedFood); G.NeedWater=Int(O,TEXT("needWater"),G.NeedWater); G.NeedJobs=Int(O,TEXT("needJobs"),G.NeedJobs); G.NeedSecurity=Int(O,TEXT("needSecurity"),G.NeedSecurity); G.NeedHealthcare=Int(O,TEXT("needHealthcare"),G.NeedHealthcare); G.UnrestPressure=Int(O,TEXT("unrestPressure"),G.UnrestPressure); G.UnrestSources=Strs(O,TEXT("unrestSources")); return G; }
    FDemocracyRegionState ParseRegion(const TSharedPtr<FJsonObject>& O){ FDemocracyRegionState R; R.RegionName=Str(O,TEXT("regionName"),R.RegionName); R.Climate=Str(O,TEXT("climate"),R.Climate); R.PopulationShare=Int(O,TEXT("populationShare"),R.PopulationShare); R.Approval=Int(O,TEXT("approval"),R.Approval); R.Stability=Int(O,TEXT("stability"),R.Stability); R.Unrest=Int(O,TEXT("unrest"),R.Unrest); R.FoodAccess=Int(O,TEXT("foodAccess"),R.FoodAccess); R.WaterAccess=Int(O,TEXT("waterAccess"),R.WaterAccess); R.Jobs=Int(O,TEXT("jobs"),R.Jobs); R.Security=Int(O,TEXT("security"),R.Security); R.Infrastructure=Int(O,TEXT("infrastructure"),R.Infrastructure); R.UnrestSources=Strs(O,TEXT("unrestSources")); return R; }
    FDemocracyDemographicsState ParseDemo(const TSharedPtr<FJsonObject>& O){ FDemocracyDemographicsState D; D.TotalPopulationThousands=Int(O,TEXT("totalPopulationThousands"),D.TotalPopulationThousands); D.AverageGroupApproval=Int(O,TEXT("averageGroupApproval"),D.AverageGroupApproval); D.AverageRegionalApproval=Int(O,TEXT("averageRegionalApproval"),D.AverageRegionalApproval); D.NationalNeedsPressure=Int(O,TEXT("nationalNeedsPressure"),D.NationalNeedsPressure); D.DemographicUnrestPressure=Int(O,TEXT("demographicUnrestPressure"),D.DemographicUnrestPressure); D.NationalUnrestSources=Strs(O,TEXT("nationalUnrestSources")); ObjArray(O,TEXT("citizenGroups"),D.CitizenGroups,ParseGroup); ObjArray(O,TEXT("regions"),D.Regions,ParseRegion); return D; }
    FDemocracyEconomyBudgetState ParseBudget(const TSharedPtr<FJsonObject>& O){ FDemocracyEconomyBudgetState B; B.TaxRate=Int(O,TEXT("taxRate"),B.TaxRate); B.TaxPolicy=Str(O,TEXT("taxPolicy"),B.TaxPolicy); B.PublicServicesSpending=Int(O,TEXT("publicServicesSpending"),B.PublicServicesSpending); B.InfrastructureSpending=Int(O,TEXT("infrastructureSpending"),B.InfrastructureSpending); B.DefenseSpending=Int(O,TEXT("defenseSpending"),B.DefenseSpending); B.Debt=Int(O,TEXT("debt"),B.Debt); B.Income=Int(O,TEXT("income"),B.Income); B.Expenses=Int(O,TEXT("expenses"),B.Expenses); B.Deficit=Int(O,TEXT("deficit"),B.Deficit); B.Inflation=Int(O,TEXT("inflation"),B.Inflation); B.PublicServices=Int(O,TEXT("publicServices"),B.PublicServices); B.ProductionEfficiency=Int(O,TEXT("productionEfficiency"),B.ProductionEfficiency); B.SpendingPosture=Str(O,TEXT("spendingPosture"),B.SpendingPosture); B.LastBudgetSummary=Str(O,TEXT("lastBudgetSummary"),B.LastBudgetSummary); return B; }
    FDemocracyResourceChainEntry ParseChain(const TSharedPtr<FJsonObject>& O){ FDemocracyResourceChainEntry C; C.ResourceName=Str(O,TEXT("resourceName"),C.ResourceName); C.Production=Int(O,TEXT("production"),C.Production); C.Consumption=Int(O,TEXT("consumption"),C.Consumption); C.Imports=Int(O,TEXT("imports"),C.Imports); C.Exports=Int(O,TEXT("exports"),C.Exports); C.Reserve=Int(O,TEXT("reserve"),C.Reserve); C.ReserveTarget=Int(O,TEXT("reserveTarget"),C.ReserveTarget); C.Shortage=Int(O,TEXT("shortage"),C.Shortage); C.Surplus=Int(O,TEXT("surplus"),C.Surplus); C.StrategicValue=Int(O,TEXT("strategicValue"),C.StrategicValue); C.Role=Str(O,TEXT("role"),C.Role); C.Status=Str(O,TEXT("status"),C.Status); C.Drivers=Strs(O,TEXT("drivers")); return C; }
    FDemocracyResourceProductionChainState ParseChains(const TSharedPtr<FJsonObject>& O){ FDemocracyResourceProductionChainState S; S.TotalShortagePressure=Int(O,TEXT("totalShortagePressure"),S.TotalShortagePressure); S.TradeBalance=Int(O,TEXT("tradeBalance"),S.TradeBalance); S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); S.Summary=Str(O,TEXT("summary"),S.Summary); ObjArray(O,TEXT("chains"),S.Chains,ParseChain); return S; }
    FDemocracyDepartmentState ParseDept(const TSharedPtr<FJsonObject>& O){ FDemocracyDepartmentState D; D.DepartmentName=Str(O,TEXT("departmentName"),D.DepartmentName); D.MinisterTitle=Str(O,TEXT("ministerTitle"),D.MinisterTitle); D.Domain=Str(O,TEXT("domain"),D.Domain); D.BudgetShare=Int(O,TEXT("budgetShare"),D.BudgetShare); D.Staffing=Int(O,TEXT("staffing"),D.Staffing); D.Effectiveness=Int(O,TEXT("effectiveness"),D.Effectiveness); D.PublicTrust=Int(O,TEXT("publicTrust"),D.PublicTrust); D.Priority=Int(O,TEXT("priority"),D.Priority); D.CurrentAction=Str(O,TEXT("currentAction"),D.CurrentAction); D.PolicyInterface=Str(O,TEXT("policyInterface"),D.PolicyInterface); D.AdvisorySummary=Str(O,TEXT("advisorySummary"),D.AdvisorySummary); D.ActionEffects=Strs(O,TEXT("actionEffects")); return D; }
    FDemocracyDepartmentSystemState ParseDepts(const TSharedPtr<FJsonObject>& O){ FDemocracyDepartmentSystemState S; S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); S.Coordination=Int(O,TEXT("coordination"),S.Coordination); S.Summary=Str(O,TEXT("summary"),S.Summary); ObjArray(O,TEXT("departments"),S.Departments,ParseDept); return S; }
    FDemocracyApprovalCauseState ParseCause(const TSharedPtr<FJsonObject>& O){ FDemocracyApprovalCauseState C; C.CauseName=Str(O,TEXT("causeName"),C.CauseName); C.Category=Str(O,TEXT("category"),C.Category); C.ApprovalImpact=Int(O,TEXT("approvalImpact"),C.ApprovalImpact); C.UnrestImpact=Int(O,TEXT("unrestImpact"),C.UnrestImpact); C.StabilityImpact=Int(O,TEXT("stabilityImpact"),C.StabilityImpact); C.Severity=Int(O,TEXT("severity"),C.Severity); C.SourceMetric=Str(O,TEXT("sourceMetric"),C.SourceMetric); C.CurrentStatus=Str(O,TEXT("currentStatus"),C.CurrentStatus); C.SuggestedResponses=Strs(O,TEXT("suggestedResponses")); return C; }
    FDemocracyApprovalStabilityModelState ParseApproval(const TSharedPtr<FJsonObject>& O){ FDemocracyApprovalStabilityModelState S; S.NetApprovalPressure=Int(O,TEXT("netApprovalPressure"),S.NetApprovalPressure); S.NetUnrestPressure=Int(O,TEXT("netUnrestPressure"),S.NetUnrestPressure); S.NetStabilityPressure=Int(O,TEXT("netStabilityPressure"),S.NetStabilityPressure); S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); S.Summary=Str(O,TEXT("summary"),S.Summary); ObjArray(O,TEXT("causes"),S.Causes,ParseCause); return S; }    FDemocracyPressReleaseRecordState ParsePressRec(const TSharedPtr<FJsonObject>& O){ FDemocracyPressReleaseRecordState R; R.Turn=Int(O,TEXT("turn"),R.Turn); R.AnnouncementType=Str(O,TEXT("announcementType"),R.AnnouncementType); R.MessageQuality=Str(O,TEXT("messageQuality"),R.MessageQuality); R.bTruthful=Bool(O,TEXT("truthful"),R.bTruthful); R.ApprovalDelta=Int(O,TEXT("approvalDelta"),R.ApprovalDelta); R.StabilityDelta=Int(O,TEXT("stabilityDelta"),R.StabilityDelta); R.DiplomacyDelta=Int(O,TEXT("diplomacyDelta"),R.DiplomacyDelta); R.UnrestDelta=Int(O,TEXT("unrestDelta"),R.UnrestDelta); R.CredibilityDelta=Int(O,TEXT("credibilityDelta"),R.CredibilityDelta); R.CredibilityAfter=Int(O,TEXT("credibilityAfter"),R.CredibilityAfter); R.Summary=Str(O,TEXT("summary"),R.Summary); return R; }
    FDemocracyPressOfficeState ParsePress(const TSharedPtr<FJsonObject>& O){ FDemocracyPressOfficeState S; S.Credibility=Int(O,TEXT("credibility"),S.Credibility); S.ConsecutiveEmptyAnnouncements=Int(O,TEXT("consecutiveEmptyAnnouncements"),S.ConsecutiveEmptyAnnouncements); S.ConsecutiveFalseAnnouncements=Int(O,TEXT("consecutiveFalseAnnouncements"),S.ConsecutiveFalseAnnouncements); S.TotalAnnouncements=Int(O,TEXT("totalAnnouncements"),S.TotalAnnouncements); S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); S.MaxRecords=Int(O,TEXT("maxRecords"),S.MaxRecords); S.LastAnnouncementSummary=Str(O,TEXT("lastAnnouncementSummary"),S.LastAnnouncementSummary); ObjArray(O,TEXT("records"),S.Records,ParsePressRec); return S; }
    FDemocracyMeetingRecordState ParseMeetRec(const TSharedPtr<FJsonObject>& O){ FDemocracyMeetingRecordState R; R.Turn=Int(O,TEXT("turn"),R.Turn); R.MeetingType=Str(O,TEXT("meetingType"),R.MeetingType); R.ParticipantName=Str(O,TEXT("participantName"),R.ParticipantName); R.AgendaItem=Str(O,TEXT("agendaItem"),R.AgendaItem); R.OutcomeSummary=Str(O,TEXT("outcomeSummary"),R.OutcomeSummary); R.ApprovalDelta=Int(O,TEXT("approvalDelta"),R.ApprovalDelta); R.StabilityDelta=Int(O,TEXT("stabilityDelta"),R.StabilityDelta); R.UnrestDelta=Int(O,TEXT("unrestDelta"),R.UnrestDelta); R.DiplomacyDelta=Int(O,TEXT("diplomacyDelta"),R.DiplomacyDelta); R.TreasuryDelta=Int(O,TEXT("treasuryDelta"),R.TreasuryDelta); R.EconomyDelta=Int(O,TEXT("economyDelta"),R.EconomyDelta); R.MilitaryDelta=Int(O,TEXT("militaryDelta"),R.MilitaryDelta); R.InfrastructureDelta=Int(O,TEXT("infrastructureDelta"),R.InfrastructureDelta); R.AdvisorCoordinationDelta=Int(O,TEXT("advisorCoordinationDelta"),R.AdvisorCoordinationDelta); R.ForeignTrustDelta=Int(O,TEXT("foreignTrustDelta"),R.ForeignTrustDelta); return R; }
    FDemocracyMeetingSystemState ParseMeeting(const TSharedPtr<FJsonObject>& O){ FDemocracyMeetingSystemState S; S.TotalMeetings=Int(O,TEXT("totalMeetings"),S.TotalMeetings); S.AdvisorCoordination=Int(O,TEXT("advisorCoordination"),S.AdvisorCoordination); S.ForeignTrust=Int(O,TEXT("foreignTrust"),S.ForeignTrust); S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); S.MaxRecords=Int(O,TEXT("maxRecords"),S.MaxRecords); S.LastMeetingSummary=Str(O,TEXT("lastMeetingSummary"),S.LastMeetingSummary); ObjArray(O,TEXT("records"),S.Records,ParseMeetRec); return S; }
    FDemocracyDevelopmentTrackState ParseTrack(const TSharedPtr<FJsonObject>& O){ FDemocracyDevelopmentTrackState T; T.TrackName=Str(O,TEXT("trackName"),T.TrackName); T.FocusArea=Str(O,TEXT("focusArea"),T.FocusArea); T.Level=Int(O,TEXT("level"),T.Level); T.Progress=Int(O,TEXT("progress"),T.Progress); T.ProgressTarget=Int(O,TEXT("progressTarget"),T.ProgressTarget); T.TreasuryCost=Int(O,TEXT("treasuryCost"),T.TreasuryCost); T.WoodCost=Int(O,TEXT("woodCost"),T.WoodCost); T.MetalsCost=Int(O,TEXT("metalsCost"),T.MetalsCost); T.FuelCost=Int(O,TEXT("fuelCost"),T.FuelCost); T.CurrentProject=Str(O,TEXT("currentProject"),T.CurrentProject); T.StrategicBenefit=Str(O,TEXT("strategicBenefit"),T.StrategicBenefit); T.Unlocks=Strs(O,TEXT("unlocks")); return T; }
    FDemocracyDevelopmentSystemState ParseDevelopment(const TSharedPtr<FJsonObject>& O){ FDemocracyDevelopmentSystemState S; S.ActiveFocus=Str(O,TEXT("activeFocus"),S.ActiveFocus); S.DevelopmentPoints=Int(O,TEXT("developmentPoints"),S.DevelopmentPoints); S.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),S.LastUpdatedTurn); S.Summary=Str(O,TEXT("summary"),S.Summary); ObjArray(O,TEXT("tracks"),S.Tracks,ParseTrack); return S; }
    FDemocracyDecisionRecordState ParseDecision(const TSharedPtr<FJsonObject>& O){ FDemocracyDecisionRecordState R; R.Turn=Int(O,TEXT("turn"),R.Turn); R.Category=Str(O,TEXT("category"),R.Category); R.DecisionTitle=Str(O,TEXT("decisionTitle"),R.DecisionTitle); R.DecisionDetail=Str(O,TEXT("decisionDetail"),R.DecisionDetail); R.ConsequenceSummary=Str(O,TEXT("consequenceSummary"),R.ConsequenceSummary); R.ApprovalAfter=Int(O,TEXT("approvalAfter"),R.ApprovalAfter); R.StabilityAfter=Int(O,TEXT("stabilityAfter"),R.StabilityAfter); R.UnrestAfter=Int(O,TEXT("unrestAfter"),R.UnrestAfter); R.TreasuryAfter=Int(O,TEXT("treasuryAfter"),R.TreasuryAfter); R.EconomyAfter=Int(O,TEXT("economyAfter"),R.EconomyAfter); R.MilitaryAfter=Int(O,TEXT("militaryAfter"),R.MilitaryAfter); R.Severity=Int(O,TEXT("severity"),R.Severity); R.TimestampUtc=Str(O,TEXT("timestampUtc"),R.TimestampUtc); R.Tags=Strs(O,TEXT("tags")); return R; }
    FDemocracyDecisionHistoryState ParseHistory(const TSharedPtr<FJsonObject>& O){ FDemocracyDecisionHistoryState H; H.LastUpdatedTurn=Int(O,TEXT("lastUpdatedTurn"),H.LastUpdatedTurn); H.MaxRecords=Int(O,TEXT("maxRecords"),H.MaxRecords); H.Summary=Str(O,TEXT("summary"),H.Summary); ObjArray(O,TEXT("records"),H.Records,ParseDecision); return H; }
    FDemocracyGeneratedCountryState ParseGenCountry(const TSharedPtr<FJsonObject>& O){ FDemocracyGeneratedCountryState C; C.CountryName=Str(O,TEXT("countryName"),C.CountryName); C.ContinentName=Str(O,TEXT("continentName"),C.ContinentName); C.Climate=Str(O,TEXT("climate"),C.Climate); C.PoliticalType=Str(O,TEXT("politicalType"),C.PoliticalType); C.DiplomaticAlignment=Str(O,TEXT("diplomaticAlignment"),C.DiplomaticAlignment); C.PowerScore=Int(O,TEXT("powerScore"),C.PowerScore); C.Stability=Int(O,TEXT("stability"),C.Stability); C.BorderPressure=Int(O,TEXT("borderPressure"),C.BorderPressure); C.bAlliedWithPlayer=Bool(O,TEXT("alliedWithPlayer"),C.bAlliedWithPlayer); return C; }
    FDemocracyContinentState ParseContinent(const TSharedPtr<FJsonObject>& O){ FDemocracyContinentState C; C.ContinentName=Str(O,TEXT("continentName"),C.ContinentName); C.Climate=Str(O,TEXT("climate"),C.Climate); C.CountryCount=Int(O,TEXT("countryCount"),C.CountryCount); ObjArray(O,TEXT("countries"),C.Countries,ParseGenCountry); return C; }
    FDemocracyWorldMapState ParseWorld(const TSharedPtr<FJsonObject>& O){ FDemocracyWorldMapState W; W.ContinentCount=Int(O,TEXT("continentCount"),W.ContinentCount); W.TotalCountryCount=Int(O,TEXT("totalCountryCount"),W.TotalCountryCount); W.DemocraticAllyCount=Int(O,TEXT("democraticAllyCount"),W.DemocraticAllyCount); W.NonDemocraticCountryCount=Int(O,TEXT("nonDemocraticCountryCount"),W.NonDemocraticCountryCount); W.GenerationRule=Str(O,TEXT("generationRule"),W.GenerationRule); ObjArray(O,TEXT("continents"),W.Continents,ParseContinent); return W; }
    FDemocracyRivalCountryState ParseRival(const TSharedPtr<FJsonObject>& O){ FDemocracyRivalCountryState R; R.CountryName=Str(O,TEXT("countryName"),R.CountryName); R.Temperament=Str(O,TEXT("temperament"),R.Temperament); R.RelationToPlayer=Str(O,TEXT("relationToPlayer"),R.RelationToPlayer); R.PowerScore=Int(O,TEXT("powerScore"),R.PowerScore); R.BorderPressure=Int(O,TEXT("borderPressure"),R.BorderPressure); R.TradeValue=Int(O,TEXT("tradeValue"),R.TradeValue); return R; }
    FDemocracyRtsWorldState ParseRts(const TSharedPtr<FJsonObject>& O){ FDemocracyRtsWorldState R; R.SimulationSecond=Int(O,TEXT("simulationSecond"),R.SimulationSecond); R.ControlledTerritories=Int(O,TEXT("controlledTerritories"),R.ControlledTerritories); R.BorderTerritories=Int(O,TEXT("borderTerritories"),R.BorderTerritories); R.KnownRivalCountries=Int(O,TEXT("knownRivalCountries"),R.KnownRivalCountries); R.ActiveStrategicLayers=Strs(O,TEXT("activeStrategicLayers")); ObjArray(O,TEXT("rivals"),R.Rivals,ParseRival); return R; }

    FDemocracySimulationState ParseState(const TSharedPtr<FJsonObject>& O){ FDemocracySimulationState S; S.Turn=Int(O,TEXT("turn"),S.Turn); S.Phase=Str(O,TEXT("phase"),S.Phase); S.RealTimeTickSeconds=Flt(O,TEXT("realTimeTickSeconds"),S.RealTimeTickSeconds); S.bPaused=Bool(O,TEXT("paused"),S.bPaused); S.PlayerCountry=ParseCountry(Obj(O,TEXT("playerCountry"))); S.FailureRisk=ParseFailure(Obj(O,TEXT("failureRisk"))); S.InvasionRisk=ParseInvasion(Obj(O,TEXT("invasionRisk"))); S.AdvisorSystem=ParseAdvisor(Obj(O,TEXT("advisorSystem"))); S.EventSystem=ParseEvents(Obj(O,TEXT("eventSystem"))); S.Demographics=ParseDemo(Obj(O,TEXT("demographics"))); S.EconomyBudget=ParseBudget(Obj(O,TEXT("economyBudget"))); S.ResourceChains=ParseChains(Obj(O,TEXT("resourceChains"))); S.Departments=ParseDepts(Obj(O,TEXT("departments"))); S.ApprovalStability=ParseApproval(Obj(O,TEXT("approvalStability"))); S.PressOffice=ParsePress(Obj(O,TEXT("pressOffice"))); S.MeetingSystem=ParseMeeting(Obj(O,TEXT("meetingSystem"))); S.DevelopmentSystem=ParseDevelopment(Obj(O,TEXT("developmentSystem"))); S.DecisionHistory=ParseHistory(Obj(O,TEXT("decisionHistory"))); S.WorldMap=ParseWorld(Obj(O,TEXT("worldMap"))); S.RtsWorld=ParseRts(Obj(O,TEXT("rtsWorld"))); return S; }

    bool BuildUpdated(FDemocracyLoadedSaveState& L,const FString& Kind,FString& Out,FString& Err){ TSharedPtr<FJsonObject> Root; if(!LoadRootFallback(L.SavePath,Root,Err)) return false; TSharedPtr<FJsonObject> StateObj; const TSharedRef<TJsonReader<>> SR=TJsonReaderFactory<>::Create(L.RuntimeState.ToJson(2)); if(!FJsonSerializer::Deserialize(SR,StateObj)||!StateObj.IsValid()){ Err=TEXT("Runtime state could not be converted to JSON for saving."); return false; } L.LastPlayedAtUtc=FDateTime::UtcNow().ToIso8601(); Root->SetNumberField(TEXT("formatVersion"),FMath::Max(1,Int(Root,TEXT("formatVersion"),1))); Root->SetNumberField(TEXT("saveVersion"),Int(Root,TEXT("saveVersion"),0)+1); Root->SetStringField(TEXT("lastPlayedAtUtc"),L.LastPlayedAtUtc); Root->SetStringField(TEXT("lastSaveKind"),Kind); Root->SetStringField(Kind.Equals(TEXT("Autosave"),ESearchCase::IgnoreCase)?TEXT("lastAutosaveAtUtc"):TEXT("lastManualSaveAtUtc"),L.LastPlayedAtUtc); Root->SetObjectField(TEXT("currentGameState"),StateObj); TSharedPtr<FJsonObject> Prot=MakeShared<FJsonObject>(); Prot->SetStringField(TEXT("autosavePath"),AutoPath(L.SavePath)); Prot->SetStringField(TEXT("backup1Path"),BakPath(L.SavePath,1)); Prot->SetStringField(TEXT("backup2Path"),BakPath(L.SavePath,2)); Prot->SetNumberField(TEXT("redundantCopies"),2); Root->SetObjectField(TEXT("saveProtection"),Prot); TSharedPtr<FJsonObject> Progress=MakeShared<FJsonObject>(); Progress->SetNumberField(TEXT("turn"),L.RuntimeState.Turn); Progress->SetStringField(TEXT("phase"),L.RuntimeState.Phase); Progress->SetNumberField(TEXT("simulationSecond"),L.RuntimeState.RtsWorld.SimulationSecond); Progress->SetBoolField(TEXT("paused"),L.RuntimeState.bPaused); Root->SetObjectField(TEXT("progress"),Progress); const TSharedRef<TJsonWriter<>> W=TJsonWriterFactory<>::Create(&Out); if(!FJsonSerializer::Serialize(Root.ToSharedRef(),W)){ Err=TEXT("Could not serialize updated save JSON."); return false; } return true; }
}

FString FDemocracyLoadedSaveState::ToSummaryText() const{ return FString::Printf(TEXT("%s | %s | %s | turn %d | continents %d | countries %d | allies %d"),*StateName,*Difficulty,*Climate,RuntimeState.Turn,RuntimeState.WorldMap.Continents.Num(),RuntimeState.WorldMap.TotalCountryCount,RuntimeState.WorldMap.DemocraticAllyCount); }

bool FDemocracySaveGameRuntime::LoadSinglePlayerSave(const FString& SavePath,FDemocracyLoadedSaveState& Out,FString& Err){ TSharedPtr<FJsonObject> Root; if(!LoadRoot(SavePath,Root,Err)) return false; TSharedPtr<FJsonObject> Cur=Obj(Root,TEXT("currentGameState")); if(!Cur.IsValid()) Cur=Obj(Root,TEXT("initialGameState")); Out=FDemocracyLoadedSaveState(); Out.FormatVersion=Int(Root,TEXT("formatVersion")); Out.SaveId=Str(Root,TEXT("saveId")); Out.StateName=Str(Root,TEXT("stateName")); Out.Mode=Str(Root,TEXT("mode")); Out.Difficulty=Str(Root,TEXT("difficulty")); Out.Climate=Str(Root,TEXT("climate")); Out.LeaderGender=Str(Root,TEXT("leaderGender")); Out.AddressTitle=Str(Root,TEXT("addressTitle")); Out.CreatedAtUtc=Str(Root,TEXT("createdAtUtc")); Out.LastPlayedAtUtc=Str(Root,TEXT("lastPlayedAtUtc")); Out.SavePath=SavePath; Out.RuntimeState=ParseState(Cur); if(Out.StateName.IsEmpty()) Out.StateName=Out.RuntimeState.PlayerCountry.CountryName; UE_LOG(LogTemp,Log,TEXT("Loaded Democracy save into runtime: %s"),*Out.ToSummaryText()); return true; }

bool FDemocracySaveGameRuntime::LoadSinglePlayerSaveWithFallback(const FString& SavePath,FDemocracyLoadedSaveState& Out,FString& Err){ TArray<FString> Errors; for(const FString& C:Candidates(SavePath,true)){ if(!FPaths::FileExists(C)) continue; FString E; if(LoadSinglePlayerSave(C,Out,E)){ if(!C.Equals(SavePath,ESearchCase::IgnoreCase)){ Out.SavePath=SavePath; Err=FString::Printf(TEXT("Loaded protected backup because the primary save was unavailable or invalid: %s"),*C); UE_LOG(LogTemp,Warning,TEXT("Recovered Democracy save from protected backup: %s"),*C); } return true; } Errors.Add(E); } Err=Errors.Num()?FString::Join(Errors,TEXT("\n")):FString::Printf(TEXT("No readable save, autosave, or backup exists for %s"),*SavePath); return false; }

bool FDemocracySaveGameRuntime::SaveSinglePlayerRuntimeState(FDemocracyLoadedSaveState& L,FString& Err){ if(L.SavePath.IsEmpty()){ Err=TEXT("No save path is available for the loaded state."); return false; } FString C; if(!BuildUpdated(L,TEXT("Manual"),C,Err)) return false; if(!WriteProtected(L.SavePath,C,true,Err)) return false; UE_LOG(LogTemp,Log,TEXT("Saved Democracy runtime state with protected backups: %s"),*L.SavePath); return true; }

bool FDemocracySaveGameRuntime::SaveSinglePlayerAutosave(FDemocracyLoadedSaveState& L,FString& Err){ if(L.SavePath.IsEmpty()){ Err=TEXT("No save path is available for autosave."); return false; } FString C; if(!BuildUpdated(L,TEXT("Autosave"),C,Err)) return false; const FString A=AutoPath(L.SavePath); if(!WriteProtected(A,C,true,Err)) return false; UE_LOG(LogTemp,Log,TEXT("Autosaved Democracy runtime state with protected backups: %s"),*A); return true; }

bool FDemocracySaveGameRuntime::GetProtectedReloadSavePath(const FString& SavePath,FString& OutReloadPath,FString& Err){ for(const FString& C:Candidates(SavePath,false)){ if(ValidSave(C)){ OutReloadPath=C; return true; } } Err=FString::Printf(TEXT("No valid protected reload save exists for %s"),*SavePath); return false; }